### ISSUE TITLE
MySQL adapter passes through ORDER BY with COUNT

### ISSUE THREAD

**Issue by paveleremin** [UnionOfRAD/lithium#1041]
When you post in Model::count(options) options with [order] you will see ORDER BY in mysql.log in generated query
It seems to me, this need to be fixed, cause ORDER BY no need for count operation. Yes i know about optimizator MySQL, but it is just the extra network traffic

**Comment by davidpersson** [comment]
@paveleremin thanks for your submission. I tried to give a good answer below.

There are many ways to create suboptimal queries or even break query generation altogether. I don't believe that a framework can/should prevent you from doing things. If we'd implement such a feature, which other cases of suboptimal queries would we miss? This would also introduce more "magicness".
