### ISSUE TITLE
[RFC] HHVM compatibility

### ISSUE THREAD

**Issue by ericcholis** [UnionOfRAD/lithium#1080]
Looks like HHVM is becoming more mature and stable, with over 22 frameworks passing 100% of the tests. Any thoughts?

http://hhvm.com/frameworks/

**Comment by davidpersson** [comment]
Current blockers

- [ ] "dechunk" stream filter is missing (https://github.com/facebook/hhvm/issues/4255)
- [ ] Differences in reflection
- [ ] Mocker uses eval (davidpersson probably has a solution)
- [ ] Differences in error msg wording
- [ ] Connection handling

https://travis-ci.org/UnionOfRAD/lithium/jobs/100208148

**Comment by davidpersson** [comment]
I'm closing this issue, we're not going to further try to support HHVM. It differs in too many ways and we never had tests pass fully. Other frameworks are dropping support for it too:
https://twitter.com/fabpot/status/865263458903875584

**Comment by davidpersson** [comment]
Removing CI builds in 130088571c6e08bafe1bb28b156e66759ea6169b
