### ISSUE TITLE
Render checkbox with checked attribut

### ISSUE THREAD

**Issue by gmercey** [UnionOfRAD/lithium#1142]
Hi,

I recently saw that the `Form` Helper renders checkbox with a `value` attribut instead of the `checked` excepted :

    <input type="hidden" name="opt_in" value="" />
    <input type="checkbox" name="opt_in" id="UserOptIn" value="1" />  

Instead of

    <input type="checkbox" name="opt_in" id="UserOptIn" checked />  

It's not a problem for the data send by the form, but it is if you're try using css selector `input:checked`
I don't know if it was done on purpose or not, so I just wondering if it can be part of an enhancement.

Thanks

**Comment by binhwpo** [comment]
Hi @gmercey From what I used, passing `$options['hidden'] = false` into the call `$this->Form->checkbox($name, $options)` function will solve your issue.

But honestly, I still wonder why would they made it a hidden field in the first place. And so yes, this should be improved.

**Comment by nateabele** [comment]
> But honestly, I still wonder why would they made it a hidden field in the first place. And so yes, this should be improved.

Because if the checkbox is unchecked when `POST`ing the form, the field would otherwise be omitted from the data entirely, making it impossible to, say, toggle off a boolean field without special logic.

**Comment by binhwpo** [comment]
@nateabele Thanks for this clarification. No wonder my checkboxes field become unset when I save the whole array... this explains it and I will need to adjust my code a bit.

**Comment by davidpersson** [comment]
Closing as per nate's explanation.
