### ISSUE TITLE
Packagist use git instead of https

### ISSUE THREAD

**Issue by alexbowers-tecmark** [UnionOfRAD/lithium#1147]
Please can the packagist.org package be changed to use the git location instead of https; this allows composer to cache lithium, so it doesn't need to be downloaded every time composer install is ran.

**Comment by alexbowers-tecmark** [comment]
I think I know why this happens.
Since we are loading a branch (dev-master), it composer doesn't cache this, it clones branches.

What most projects seem to do is set up on packagist releases.

I suggest that we mark a new release on packagist, so that that version can be loaded and cached.

**Comment by alexbowers** [comment]
@nateabele ^^

**Comment by davidpersson** [comment]
Using branches with composer will almost always lead to cloning the branch. You can use tagged releases to download zip packages. 
```json
{
    "require": {
        "unionofrad/lithium": "1.0-beta"
    }
}
```

As a sidenote: We'll retag releases to follow semver version numbering scheme, to increase compatibility with composer. That however doesn't affect the usage scheme above.

**Comment by alexbowers** [comment]
My issue with this is that that release does not pull in a few of the latest commits on master.

The 1.0-beta tag was created Aug 2013, but there are commits on master branch from 2014.

Can a new tag be created, so that I can reference  that commit.

**Comment by davidpersson** [comment]
This is what I have in my composer projects and it works fine.

```json
{
    "require": {
        "minimum-stability": "dev",
        "unionofrad/lithium": "dev-dev as 1.0.0-dev"
    }
}
```

Instead of dev-dev just use dev-master.

**Comment by alexbowers-tecmark** [comment]
@davidpersson This hasn't appeared to work. It still performs a clone each time.

This is what we have for the require line. 

``` json
"unionofrad/lithium": "dev-master as 1.0.0-dev",
```

Can we not just get the current version of Li3 to be tagged as a new release. This would solve all of the problems.

**Comment by davidpersson** [comment]
@alexbowers-tecmark Using branches will always lead to composer cloning the repo. There's nothing that lithium does special in that regard. re: tagging we're working on this.

**Comment by davidpersson** [comment]
And: if some commits are missing from a branch be sure to empty your composer cache.
