### ISSUE TITLE
Question: Lithium Model Inheritance

### ISSUE THREAD

**Issue by binhwpo** [UnionOfRAD/lithium#1156]
Hi Team,

We all know that functions are inherited, but how about the protected `$_schema`?

For example, I have:

```php
class ParentModel extends Model {
 protected $_schema = array(
  'name' => array('type' => 'string'),
  'address' => array('type' => 'string'),
}

class ChildModel extends ParentModel {
 protected $_schema = array(
  'mobile' => array('type' => 'string'),
  'email' => array('type' => 'string'),
}
```
I wonder when saving a `ChildModel` record, would the `$_schema` of `ChildModel`   combined with the `$_schema` of `ParentModel`? That's:

```php
array(
  'name' => array('type' => 'string'),
  'address' => array('type' => 'string'),
  'mobile' => array('type' => 'string'),
  'email' => array('type' => 'string'),
);
```

How can I check if this is the case?

Big Thanks

**Comment by nateabele** [comment]
> I wonder when saving a ChildModel record, would the $_schema of ChildModel combined with the $_schema of ParentModel?

Yes. Please direct further questions to StackOverflow. Thanks.

**Comment by binhwpo** [comment]
@nateabele Thanks for pointing me to the right direction. Since it's directly related to Lithium I hope you might spare some time to answer: http://stackoverflow.com/questions/27853947/does-chema-get-inherited-in-lithium-parent-child-model

Your cooperation is greatly appreciated.

Thanks.

**Comment by rmarscher** [comment]
@nateabele @binhwpo I answered the question on StackOverflow.

**Comment by binhwpo** [comment]
@nateabele @rmarscher You guys are awesome! Really appreciated and big thanks.
