### ISSUE TITLE
SQL Injection Security Flaw

### ISSUE THREAD

**Issue by DrRoach** [UnionOfRAD/lithium#1157]
[protected]

[

The issue text has temporarily been removed. Please do not disclose potential security related bugs publicly see http://li3.me/development#security for more information on the topic. @nateabele will get in touch with you regarding the original issue during the next 48hrs.

]

**Comment by davidpersson** [comment]
@DrRoach Please see above explanation why this issue has been updated.

**Comment by DrRoach** [comment]
Okay sorry about that
