### ISSUE TITLE
Model::find() returns no results with Mongo driver version 1.6.0 RC1 and above

### ISSUE THREAD

**Issue by ericcholis** [UnionOfRAD/lithium#1160]
I upgraded my local mongo driver from 1.5.8 to 1.6.0 via pecl and immediately experienced a bug where all Model::find() calls returned no results. However, passing the `"calculate" => true` query parameter shows that the `MongoCursor` instance does indeed have results. Working on writing a test for this, but in the meantime here's a quick snippet to replicate the bug:

````
$created_at = time();

$query = array(
	"conditions" => compact("created_at"),
	"fields" => array( "_id" ),
	"calculate" => true
);

$entry = \lithium\tests\fixture\model\gallery\Galleries::create(compact("created_at"));
$entry->save();

$entries = Galleries::find("all", $query);

$records = $entries->count();
````

If you `unset($query["calculate"])` and re-run the query, no results are found. I'm debugging through `MongoDb::read()` and `Model::create()` to see where the issue lies.

My local environment is on OS X, PHP 5.5.21, and running `unionofrad/lithium       dev-dev 7402f43`. I've experienced the bug on two separate, but similar machines.

**Comment by ericcholis** [comment]
Seems that this bug is known: https://jira.mongodb.org/browse/PHP-1382. Here's an even simpler test from that bug report:

````php
$mongo = new \MongoClient('mongodb://127.0.0.1');
$db = $mongo->selectDb('result_test');
$coll = $db->selectCollection('tests');
$coll->save(['_id' => 'test1']);
$coll->save(['_id' => 'test2']);
$coll->save(['_id' => 'test3']);
$cur = $coll->find(['_id' => new \MongoRegex('/^test.*$/')], ['_id']);

$result = array();

while ($cur->hasNext()) {
	$arr = $cur->getNext();
	$result[] = $arr['_id'];
}

print_r($result)
````

Under 1.6.x, the third result returns `null`

**Comment by davidpersson** [comment]
Thanks for reporting @ericcholis. I'm closing as this is an upstream bug and it has already been fixed in https://github.com/mongodb/mongo-php-driver/pull/823/files. Guess we'll now have to wait for 1.6.1.

**Comment by ericcholis** [comment]
Don't think it needs to be reopened, but there's still issues upstream with the PHP Mongo 1.6.x driver. Seems that `MongoCollection::hasNext()` has been fubar since the 1.6.0 release. 

The current issue centers around `MongoCollection::hasNext()` returning false for limit=1 results
https://jira.mongodb.org/browse/PHP-1402

They should be releasing 1.6.4 on March 3rd, I'll update ASAP with some test results.

Tagging issues #1164 and #1165, for reference.
