### ISSUE TITLE
Read Issues with mongo-1.6.x PHP Driver

### ISSUE THREAD

**Issue by fitzagard** [UnionOfRAD/lithium#1164]
I haven't narrowed down the cause yet but there are read issues when using Model::first() on mongo-1.6.x driver instances. So far everything from mongo-1.5.8 and older works fine.

**Comment by davidpersson** [comment]
Can you verify if those might be related to #1160?

**Comment by ericcholis** [comment]
It's likely still upstream, but I'm having issues with 1.6.1 as well. They appeared to have fixed the issue with `MongoCursor::getNext()` incorrectly returning `null`. However, I can confirm that `Model::first()` isn't functioning as expected. `Collection::$_data` isn't being populated, thus `Collection::rewind()` can't return the first result. 

I'll step through and see where the failure is.

**Comment by fitzagard** [comment]
@ericcholis thanks for the help. I'll see what I can dig up as well.

**Comment by davidpersson** [comment]
@ericcholis @fitzagard merci!

**Comment by davidpersson** [comment]
Probably this is https://jira.mongodb.org/browse/PHP-1390

**Comment by ericcholis** [comment]
@davidpersson That's likely it.

1.6.2 is available via PECL now. My initial testing shows that 1.6.2 is working as intended, but I'm sticking to 1.5.8 for the time being. I plan on keeping an eye on the PHP MongoDB Driver JIRA from now on.

Seems odd that this and #1160 made it to release.

**Comment by davidpersson** [comment]
Alright, thanks for testing. Feel free to reopen should the issue persist.
