### ISSUE TITLE
list Model Finder

### ISSUE THREAD

**Issue by DrRoach** [UnionOfRAD/lithium#1166]
Hi,

If you try and do `Model::list();` you get a fatal exception because list is a protected function in PHP and so you need to use `Model::find('list', array());`

This isn't really clear in the documentation so could this be changed? Or should the method be changed to make it consistent with the others?

Thanks

**Comment by davidpersson** [comment]
I think this is best documented in the manual (as explaining all gotchas in the API docs would make them very verbose). Feel free to submit a new ticket or better pull request against the following document:

https://github.com/UnionOfRAD/manual/blob/dev/en/models/querying.md

**Comment by DrRoach** [comment]
Okay, I will create the pull request now, shall I also add the mongo password thing that we spoke about via email a while ago?

**Comment by davidpersson** [comment]
For that I'd use:
https://github.com/UnionOfRAD/manual/blob/dev/en/models/connections.md
or
https://github.com/UnionOfRAD/manual/blob/dev/en/security/README.md

Thanks!

And I think referring to the original study/post as well as noting "secure your mongodb" is enough. In the end it is not up to the framework to explain proper system administration.
