### ISSUE TITLE
Entity::export passed object, expects array

### ISSUE THREAD

**Issue by alexbowers-tecmark** [UnionOfRAD/lithium#1176]
https://github.com/UnionOfRAD/lithium/blob/master/data/source/Database.php#L745

This here is passing $this, which is an object into Entity::export (derived from the ::create command).

The method it gets to is this:

https://github.com/UnionOfRAD/lithium/blob/master/data/Entity.php#L460-L467

Which expects the input to be an array. Obviously, this is passing an array into it; causing a catchable fatal error.

Some insight into this would be helpful.

**Comment by alexbowers-tecmark** [comment]
Also, something to ask is why we are passing $this into export at all, when the method expects options; and never uses that at all.

**Comment by jails** [comment]
`$context` in https://github.com/UnionOfRAD/lithium/blob/master/data/source/Database.php#L745 should be an instance of `Query` https://github.com/UnionOfRAD/lithium/blob/master/data/model/Query.php#L551 not `Entity`

**Comment by alexbowers-tecmark** [comment]
How can it be if it gets $context from https://github.com/UnionOfRAD/lithium/blob/master/data/source/Database.php#L744 which defines the $context to be $type. $type is said to be either CRUD or join. 

I just logged out the value of $type, and it is an object saying: 

```
lithium\data\entity\Record::__set_state(array(
   '_model' => 'app\\models\\ProductReviews',
   '_data' =>
  array (
    'id' => '1',
    'approved' => true,
    'deleted' => false,
    'product_id' => '1',
    'customer_id' => '3',
    'review' => 'This t-shirt fits really well. Very happy.',
    'rating' => 3,
    'created' => '2015-03-24 16:17:36',
  ),
   '_relationships' =>
  array (
  ),
   '_parent' => NULL,
   '_errors' =>
  array (
  ),
   '_updated' =>
  array (
    'id' => '1',
    'approved' => true,
    'deleted' => false,
    'product_id' => '1',
    'customer_id' => '3',
    'review' => 'This t-shirt fits really well. Very happy.',
    'rating' => 3,
    'created' => '2015-03-24 16:17:36',
  ),
   '_increment' =>
  array (
  ),
   '_exists' => true,
   '_schema' =>
  array (
  ),
   '_handlers' =>
  array (
    'stdClass' =>
    Closure::__set_state(array(
    )),
  ),
   '_autoConfig' =>
  array (
    'classes' => 'merge',
    0 => 'parent',
    1 => 'schema',
    2 => 'data',
    3 => 'model',
    4 => 'exists',
    5 => 'pathKey',
    6 => 'relationships',
    7 => 'handlers',
  ),
   '_config' =>
  array (
    'model' => 'app\\models\\ProductReviews',
    'data' =>
    array (
      'approved' => true,
      'deleted' => false,
      'product_id' => '1',
      'customer_id' => '3',
      'review' => 'This t-shirt fits really well. Very happy.',
      'rating' => 3,
    ),
    'defaults' => true,
    'relationships' =>
    array (
    ),
    'init' => true,
  ),
   '_methodFilters' =>
  array (
  ),
))
```

Which is a type of Record (extending Entity), which having an ->export($this); happen on it takes it to Entity::export();

**Comment by alexbowers-tecmark** [comment]
This is the code that calls it (and commenting it out gets rid of the issue)

``` php
ProductReviews::create([
                            'product_id'  => $product->id,
                            'customer_id' => $customer->id,
                            'review'      => $details['reviews']['review'],
                            'rating'      => $details['reviews']['rating'],
                            'approved'    => ( isset( $details['reviews']['approved'] ) ? $details['reviews']['approved'] : null ),
                        ])->save();
```

**Comment by jails** [comment]
All I can say is if `$type` is an object it should be an instance of `Query` not an instance of `Entity`. The tests shows how renderCommand should be used https://github.com/UnionOfRAD/lithium/blob/791c2ce345b63cd47f067cdebccb6497a35de014/tests/cases/data/source/DatabaseTest.php#L245

**Comment by alexbowers-tecmark** [comment]
We have managed to fix our code internally. Unsure what exactly was causing this, but I think that the li3 core is fine. I'll close
