### ISSUE TITLE
Html helper tag-start and tag-end methods

### ISSUE THREAD

**Issue by DMcP89** [UnionOfRAD/lithium#1186]
Hi, I am using li3 for a project I am working on and have noticed that the Html view helper has many tags in its _strings array but does not have methods to render all of those tags. From what I can tell there are only methods for  link, image, head, script, style, and meta-link. So I started to implement a few of the methods myself as I needed them. I started with tag-start and tag-end as I figure this would be the most useful for me. Have these already been implemented? 

```PHP
public function tag_start($name,array $options = array()){
   $defaults = array();
   $options += $defaults;
   $params = compact('name','options');
   $method = __METHOD__;
   return $this->_filter($method,$params, function($self, $params, $chain) use ($method, $name){
      return $self->invokeMethod('_render', array($method, 'tag-start',$params));
       });
    }

public function tag_end($name){
   $params = compact('name');
   $method = __METHOD__;
   return $this->_filter($method,$params, function($self, $params, $chain) use ($method, $name){
      return $self->invokeMethod('_render', array($method, 'tag-end',$params));
   });
}
```

**Comment by davidpersson** [comment]
Hi @DMcP89,

Thanks for your suggestion.

There is some history around this feature. This goes back to old CakePHP days, which html helper had such a feature. We learned that making generic tag building available leads to other problems. We don't want to encourage writing you HTML in PHP. Nor do want to encourage writing JS in PHP (another problem and even worse).

We've decided in the very beginning that we don't want to support this out of the box. This is an opinionated framework. However we suggest that users in need of this functionality, subclass the html helper and add those methods.

Hope this clears some things up!
