### ISSUE TITLE
Create many

### ISSUE THREAD

**Issue by alexbowers** [UnionOfRAD/lithium#1187]
I couldn't find in the documentation anyway to create many rows in the database with just one call.

There is update for editing / updating, but create doesn't appear to have any documentation about how to do this.

Is this possible?

**Comment by davidpersson** [comment]
No there is currently no way to batch create entities. #911 is somewhat related. But at the moment we're not planning on implementing this. As this is a bug tracker, general questions are best created on SO:
https://stackoverflow.com/tags/lithium
