### ISSUE TITLE
Searching for Mongo ObjectIds in fields other than _id

### ISSUE THREAD

**Issue by DMcP89** [UnionOfRAD/lithium#1188]
Hi, 

I have a document setup in my MongoDB setup like this:

    db.find.match_reports({"_id" : ObjectId("55497d3002a6ce36393c0828")});
    {
    "_id" : ObjectId("55497d3002a6ce36393c0828"),
    "match_id" : ObjectId("55497d3002a6ce36393c0827"),
    "Type" : "Hockey",
    "Winner_Username" : Null
    "Loser_Username" : Null
    }

I know that when you call a find based on the _id field you can just pass a string, so for example:

    MatchReports::find('55497d3002a6ce36393c0828');

will return the document above. The issue I ran into was with calling a find on the match_id field. I assumed it would work similar to a find on the _id field since they were both ObjectIds, so I tried this:

    $matchReport = MatchReports::find('first', array('conditions' => array('match_id' => "55497d3002a6ce36393c0827")));

I found I had to call the find using a MongoId object instead of a plain string, which in hindsight makes sense, but it would be nice to be able to search for ObjectIds based on strings alone. Is this expected behavior and are there any plans to implement a feature like this into the Model::find method?

**Comment by nateabele** [comment]
What does your `$_schema` look like? It should cast string IDs to `MongoId`s if the field is identified as an `id` in the schema.

**Comment by DMcP89** [comment]
I don't currently have a $_scheme set for this model. I will give that a try, thanks for the tip.
