### ISSUE TITLE
Query Caching [InnoDB MySQL]

### ISSUE THREAD

**Issue by alexbowers-tecmark** [UnionOfRAD/lithium#1192]
In InnoDB, i have enabled query caching. I have proved this by getting an exact copy of the query string ran in Lithium, and pasting it directly into adminer. Running it the first time, it takes 0.3 seconds. Running it again takes 0.001 second. Now, with Lithium, every time i run it it takes the 0.3 seconds. For some reason, the query caching isn't being caught on. Even though the query is identical. Is there something being added to the query every time that isn't being caught by the query string to invalidate the cache for some reason?

Thanks.

**Comment by alexbowers-tecmark** [comment]
Further research shows it may be due to Prepared Statements. Unsure completely, but i cannot find anything specific in lithium to disable caching, so i guess its the PDO / prepared statements.

**Comment by davidpersson** [comment]
We're not using PDO prepared statements, yet (it might come in > 1.0). I'll check if I can reproduce the behavior you are seeing. 

My first guess is there is some other query invalidating the query cache before you get to it. Try switching on mysql query logging and tailing it to see the actual queries being made:
`mysqld  start --general_log_file=/tmp/my.log --general_log`

**Comment by alexbowers-tecmark** [comment]
Oh.

Is the querystring that is generated in the object (Products::save() etc), not the actual query sent to the database?

If it is, then the queries are byte-identical (already checked that). 

Small sidenote; how do we request features for the 1.0?

**Comment by davidpersson** [comment]
You can always open feature request with a detailed description in this issue tracker and label them accordingly (enhancement, optimization, rfc). There will be no new features for 1.0, because it's in stabilization period. For 1.x we'll accept non-BC-breaking changes only all the other one will be targeted in a future major release.

**Comment by davidpersson** [comment]
Regarding the query string, you better check the mysql log as I described, to be really sure what's been send to the DB.

**Comment by davidpersson** [comment]
Prepared statements are no requirement to enable query caching:
http://dev.mysql.com/doc/refman/5.7/en/query-cache-operation.html

There is nothing mutating the same query in the framework.
