### ISSUE TITLE
Mongodb PHP connection pool

### ISSUE THREAD

**Issue by nrupen92** [UnionOfRAD/lithium#1194]
I am using mongodb replicaiton with PHP Lithium on the production. I want to manage connection pool in mongodb. I have tried many options like MongoPool::size() and other options which were there in the PHP manaul. There are not working for me. I am stressing my system and i need to increase connection pool to handle the load.

Is there any way that i can manage number of connections in mongodb or by passing parameters in connection string. Currently i have connection timeout, socket timeout, wtimeout parameters in the mongodb connection string.

I have also found that connections are managed by PHP-Mongo drivers.

Also refered this for connection pooling http://docs.mongodb.org/manual/reference/connection-string/

Any idea, How to implement this in PHP?

**Comment by davidpersson** [comment]
As far as I can see the pooling mechanism has been removed for the mongo driver >= 1.3.0. Lithium however requires the >= 1.3.0. 

http://php.net/manual/en/changelog.mongo.php

These are the valid options when creating a connection:
https://github.com/UnionOfRAD/lithium/blob/dev/data/source/MongoDb.php#L126-L147

Also you can always access a model's underlying connection object by: `Posts::connection()`
