### ISSUE TITLE
Inflector turns the word 'taxes' to 'taxis'

### ISSUE THREAD

**Issue by DrRoach** [UnionOfRAD/lithium#1199]
When singularizing the word taxes, the word 'taxis' is returned. This is wrong in the case of a countries taxes where the singular should be 'tax' but it turns out the word 'taxis' is the singular of the word 'taxes' in biology and medicine. Is there any way that this can be fixed for both cases?

**Comment by davidpersson** [comment]
Please open a pull request against `dev`, this should be `tax`. Taxes -> Tax is more common (and probably what the user intended). The rule can then be overridden by anyone meaning Taxis.

**Comment by davidpersson** [comment]
See #1198 for an example PR.

**Comment by DrRoach** [comment]
Created the pull request. Sorry it took so long. #1204

**Comment by davidpersson** [comment]
Closing in favor of #1204.
