### ISSUE TITLE
php7 compatibility: `String` is a special class name

### ISSUE THREAD

**Issue by rpkamp** [UnionOfRAD/lithium#1205]
As it stands now Lithium won't run under PHP7 because 

```
PHP Fatal error:  Cannot use lithium\util\String as String because 'String' is a special class name in /path/to/unionofrad/lithium/lithium/core/Libraries.php on line 12
```

and more locations as well.

So the `String` class should be renamed to something else in order for lithium to run under PHP7.
For BC it is probably possible to keep the existing `String` class for now and delegate all calls to the new class in case people are using it in userland, and then remove it when PHP7 is mainstream.
Or alternatively it could be removed entirely forcing people to migrate immediately, getting them a step closer to being PHP7 compatible in the process.

I wouldn't mind tackling this issue, but would like to know what others think first. More specifically

* What should the name of the class be? Maybe `Strings`? Kind of contradicts with other classes in the same namespace which are all singular, but it's closest to the current name.
* What to do with BC?

**Comment by davidpersson** [comment]
1.1 will be PHP 7 compatible. The String rename already took place there (8cb0dfb7c4e8b89c6c4e852a1e172c69fef78a9e). Note that this not the only naming issue we want to solve before PHP 7. `Object` is also on the list of newly reserved keywords.
