### ISSUE TITLE
Using non-existing fields in finder

### ISSUE THREAD

**Issue by lukassivak** [UnionOfRAD/lithium#1209]
After migration to v1.0.0-rc1 i experience problems with finder. When i am using non-existing field in finder, like in example, then only one record is returned. When the field is removed, then correct number of records is returned. I am using non-existing fields for sub selects.

```
$users = Users::all(array(
    'conditions' => array(
        'status' => 1
    ),
    'fields' => array(
         'id',
         '(SELECT 1) as number'
    )
));
```

The problem is appearing after commit 9e5351afaace3dd8c4366f9e70ff2da77a371d03 - "Ensure primary record set stays in order.".

**Comment by davidpersson** [comment]
Hey thanks for the bug report. 2dc4dca contains the bug fix, please test if it fixes the issue.

The key index determination algorithm was refactored (in the commit you've referenced) but this had undetected side effects. It had problems with results without a primary and results where the primary key came after i.e. "virtual" fields.

**Comment by lukassivak** [comment]
Great, it is working now fine.
