### ISSUE TITLE
Can't add metadata tags in header

### ISSUE THREAD

**Issue by matysanchez** [UnionOfRAD/lithium#1214]
Hello friends,

I am trying to add meta data tags in header, this is my code:

app/extensions/helper/FacebookHtml.php

```php
<?php
namespace app\extensions\helper;

class FacebookHtml extends \lithium\template\Helper {

	protected $_strings = array(
		'title' => '<meta property="og:title" content="{:contenido}" />',
		'site_name' => '<meta property="og:site_name" content="{:contenido}" />',
		'url' => '<meta property="og:url" content="{:contenido}" />',
		'description' => '<meta property="og:description" content="{:contenido}" />',
		'image' => '<meta property="og:image" content="{:contenido}" />',
		'image' => '<meta property="og:image" content="{:contenido}" />',
		'locate' => '<meta property="og:locate" content="{:contenido}" />',
	);

	public function meta($contenido, $options) {
		return $this->_render(__METHOD__, $options['type'], compact('contenido'));
	}
}
```

In app/views/layout/default.html.php, inside <head>

```
<?=$this->FacebookHtml(); ?>
```

In other view file:

```
<?=$this->FacebookHtml->meta('title', 'Test.. 1...2...3...'); ?>
```

I look for hours in Google and in the core code to know how to add metadata.

**Comment by davidpersson** [comment]
For general support you'll get better answers at stackoverflow (tag with "lithium"). If this turns out to be a bug feel free to reopen.

https://stackoverflow.com/questions/tagged/lithium

**Comment by matysanchez** [comment]
@davidpersson sure, sorry about this. Here is my question, if you have one minute please check it out :)

**Comment by matysanchez** [comment]
@davidpersson @nateabele sorry to use this via to ask this question, I am looking for a solution of my problem, I read a lot and search a lot too, but I can't figure out how to do this. Please gift me one minute of your time :)
http://stackoverflow.com/questions/33220085/adding-meta-tags-in-header-in-lithium-php
