### ISSUE TITLE
Can't Extend Built-in Helpers

### ISSUE THREAD

**Issue by vbresults** [UnionOfRAD/lithium#1217]
@davidpersson It seems someone else has this issue too https://gist.github.com/jblotus/1159576

**Comment by davidpersson** [comment]
That gist is 4 years old. I'm extending the form helper in an app myself. Can you provide more details in which case/setup it is not working for you?

**Comment by vbresults** [comment]
I created a file called Form.php in app\extensions\helper;

```php
namespace app\extensions\helper;

class Form extends lithium\template\helper\Form {
	public function password($name, array $options = array()) {
		list($name, $options, $template) = $this->_defaults(__FUNCTION__, $name, $options);
		// *snip* unset($options['value']);
		return $this->_render(__METHOD__, $template, compact('name', 'options'));
	}
}
```

Then in a view I use..

```
$this->form->field("password", ['type' => "password"]);
```

The password value is stays unset.

**Comment by vbresults** [comment]
Update: this was happening because there was a forward slash on the extended class, sorry @davidpersson
