### ISSUE TITLE
Bot Logs Down

### ISSUE THREAD

**Issue by vbresults** [UnionOfRAD/lithium#1218]
The bot logs url is down.  http://li3.me/bot/logs/li3

**Comment by davidpersson** [comment]
We're now focusing on SO as the primary support platform. The IRC channels still exist but have too little activity which would suffice maintaining the bot + logs.

https://stackoverflow.com/questions/tagged/lithium

**Comment by vbresults** [comment]
@davidpersson The logs have priceless information, even if the channels are dead now, can you put the logs back up?

**Comment by davidpersson** [comment]
I see :) I'll bring them back up as soon as I get to the site again. https://github.com/UnionOfRAD/site/issues/3
