### ISSUE TITLE
Lithium Capabilities

### ISSUE THREAD

**Issue by nisarg34** [UnionOfRAD/lithium#1219]
Hi Lithium Team,

My client is considering LIthium for their forum related requirements.
So which all capabilities Lithium has out of the box for Forum/Community related?

Also, just wanted to check if Lithium supports (out of the box or by plugin) below functionalities:

SSO with SAML
Enterprise Search
3rd Party Java Application Integration
Unified Document Management
Document Preview
Blogs/Wikis/Polls
Content Management
Community Health 
Roles and Permission Management (Hierarchical and Inheritable)
Integrate Quartz Scheduler
Social Equity - Dynamic social capital system by measuring the contribution and participation of a user and the information value of an asset. A person can gain equity by performing certain activities within communities, such as adding contributions (e.g., wikis, blogs), rating or commenting, and viewing content.

Looking forward to hear from you

Thanks.

**Comment by davidpersson** [comment]
Hi @nisarg34,

Lithium is "just" the framework and can become the foundation of the features you described. You - however - will then need to build these features on your own.

Please don't use this issue tracker for general requests, this is not a support forum. You'll better ask those questions on other software related forums. Please don't crosspost.

Thanks!
