### ISSUE TITLE
Redirect with input

### ISSUE THREAD

**Issue by fedeisas** [UnionOfRAD/lithium#1221]
Hi there! One of the thinks I like from other frameworks is how they handle failed POST requests.

Instead of handling form presentation and form processing within the same controller method, you can have two methods like:
```php
class Controller
{
  public function edit()
  {
    return 'edit form view';
  }

  public function store()
  {
    // Process form
    // If validation fails, redirect to 'edit()' with input
  }
}
```

They way they do it is saving the input in session and retrieving it on the next page view.

Is this a feature would you like to include within the `Controller` object?

Thanks

**Comment by davidpersson** [comment]
Hi @fedeisas,

Thanks for submitting your ideas. First the framework is flexible enough to handle your use case without introducing new features. See the following example. Second I don't think using the session for POST data is good way to handle this case.

```php
class PostsController extends \lithium\action\Controller {

    public function edit() {
        $post = Posts::create(Session::read('default', 'post'));
        return compact('post');
    }

    public function store() {
        $post = Posts::create($this->request->data);

        if ($post->save()) {
            return $this->redirect('Posts::index');
        }
        Session::save('default', 'post', $post);
        return $this->redirect('Posts::edit');
    }
}
```
