### ISSUE TITLE
Tests Failing Locally (testMediaTypes)

### ISSUE THREAD

**Issue by shopblocks** [UnionOfRAD/lithium#1225]
While running the tests locally, I have an issue which says: 

```
Failed assertion assertEqual.
 File    : /var/www/vhosts/lithium/tests/cases/net/http/MediaTest.php
 Class   : lithium\tests\cases\net\http\MediaTest
 Method  : testMediaTypes()
 Line    : 39
 ________
trace: [0]
expected: array (
  0 => 'html',
  1 => 'htm',
  2 => 'form',
  3 => 'json',
  4 => 'rss',
  5 => 'atom',
  6 => 'css',
  7 => 'js',
  8 => 'text',
  9 => 'txt',
  10 => 'xml',
)
result: array (
  0 => 'view-integration-test',
  1 => 'html',
  2 => 'htm',
  3 => 'form',
  4 => 'json',
  5 => 'rss',
  6 => 'atom',
  7 => 'css',
  8 => 'js',
  9 => 'text',
  10 => 'txt',
  11 => 'xml',
)
```

Do you have any idea why this would be failing? 

Is there a specific setup I need to test this properly.

I currently just have the repository cloned and run `bash console/li3 test tests`

**Comment by davidpersson** [comment]
Please also state the version you are using.

**Comment by shopblocks** [comment]
It is failing for me locally on the master, 1.0 and 1.1 branches.

**Comment by shopblocks** [comment]
Ignoring all the older branches for now, Im just going to try to get 1.1 working locally in terms of tests.

The tests are inconsistent it appears.

I have just ran them twice, seeing what the results are these two times.

![image](https://cloud.githubusercontent.com/assets/14819903/11839886/4ad9f7ec-a3e9-11e5-876f-71dd43cec242.png)

![image](https://cloud.githubusercontent.com/assets/14819903/11839888/50e0c468-a3e9-11e5-9e04-1a0545fec153.png)

These tests were ran literally seconds apart.

**Comment by davidpersson** [comment]
This is indeed strange behavior. You can get more inside using the "--verbose" argument when running the tests. This will help identify which tests bounce between red/green.

**Comment by davidpersson** [comment]
The other behavior needs to be investigated in the PHP 7 ticket.
