### ISSUE TITLE
Naming of Traits

### ISSUE THREAD

**Issue by davidpersson** [UnionOfRAD/lithium#1226]
We'll start using traits in 1.1, thus we'll need to determine how the classes and files should be named. I'm currently aware of two options:

1. `core\Respondable`
2. `core\RespondsToTrait`

What do you think?

(This issue blocks progress of #1224 as we need traits for i.e. `Object` class)

**Comment by shopblocks** [comment]
Personally, I find 'Respondable' to read better. It explains what the class should be able to do after it is implemented.

As in, 'It will be able to respond'

**Comment by shopblocks** [comment]
Though, if we are to follow PSR2, then the second option is preferable.

https://github.com/php-fig/fig-standards/blob/master/bylaws/002-psr-naming-conventions.md

**Comment by shopblocks** [comment]
However, we do not follow this convention with abstract or interfaces.

I think we should at least be consistent with the naming conventions.

**Comment by davidpersson** [comment]
Then I'd vote for `FooBarTrait` following the PSR2 bylaw. @shopblocks you're right we don't follow these for abstract classes but this can become a goal for 2.0.

**Comment by shopblocks** [comment]
Im happy with PSR2 also. At least then we have documentation we can point other contributors towards as well.

Do we currently have anything like PHP-cs-fixer to enforce the PSR2?

**Comment by davidpersson** [comment]
We don't/wont follow PSR2 but the naming conventions are OK. We have our own CS checker (unionofrad/quality).

**Comment by shopblocks** [comment]
How does this get ran? I cant see it anywhere within the actual project. Does this have to be pulled in separately?

**Comment by davidpersson** [comment]
Yes it needs to be installed as a plugin.

**Comment by davidpersson** [comment]
So for the time being I'd suggest using `FooTrait`.

**Comment by nateabele** [comment]
Is PSR-2 conformance a big concern to you? I don't think it's that important. I prefer (1).

**Comment by davidpersson** [comment]
No it's not a big concern to me - any convention is good to me. Than lets go with (1), it's a bit more beautiful :)

**Comment by davidpersson** [comment]
Added to the coding standard https://github.com/UnionOfRAD/specs/commit/4c11b5fdc72a9f7a291fa4be1ea29a3dd4892862
