### ISSUE TITLE
Getting raw output from commands

### ISSUE THREAD

**Issue by shopblocks** [UnionOfRAD/lithium#1227]
Currently, there are only two ways to get output from the tests running. Either it has ANSI colours, or it is JSON formatted.

I think having a plain text format would be helpful, especially when wanting to pipe it into a different file, for example, posting into GitHub issues.

**Comment by shopblocks** [comment]
Example implementation and usage
https://github.com/UnionOfRAD/lithium/pull/1228

**Comment by shopblocks** [comment]
Now has a flag for `--no-color` instead

**Comment by shopblocks** [comment]
Was merged in.

**Comment by shopblocks** [comment]
*was not merged in*

**Comment by davidpersson** [comment]
My bad!

**Comment by shopblocks** [comment]
Dont worry, it was my bad. I thought this was merged. It was the other test one that got merged. Though i think this one is ready for merging also.

**Comment by davidpersson** [comment]
See #1228 comments.
