### ISSUE TITLE
PHP 7 Segmentation Fault when running the tests.

### ISSUE THREAD

**Issue by shopblocks** [UnionOfRAD/lithium#1236]
Locally, I get a segmentation fault, being caused by the `testDeprecatedInit()` method in `LibrariesTest.php`

It is calling `MockInitMethod::li3()`.

If i place a `trigger_error('Deprecated', E_USER_DEPRECATED);` in there, it passes fine, without any segmentation faults.

Not sure what the cause of all of this is, but it perhaps needs looking into a bit deeper. May be an issue with the PPA im using for PHP 7, but its the best one available for Ubuntu 14.04 64-bit.

**Comment by shopblocks** [comment]
@davidpersson Are you able to explain what this test should be doing?

```php
public function testDeprectatedInit() {
		$this->assertException("/Deprecated/", function() {
			MockInitMethod::li3();
		});
	}
```

**Comment by alexbowers** [comment]
Still exists in 7.0.1. Will investigate more later.

**Comment by davidpersson** [comment]
This might help when debugging segfaults:
https://bugs.php.net/bugs-generating-backtrace.php

**Comment by alexbowers** [comment]
This is the latest that I have now:

php: /home/vagrant/php-src/Zend/zend_execute.c:2466: cleanup_unfinished_calls: Assertion `op_num' failed.

**Comment by alexbowers** [comment]
The segmentation fault only happens when it is static function. Convert it to non-static and it passes fine. Not sure what this means.

**Comment by alexbowers** [comment]
Ignore the above. It now seems to be coming from the Exception being thrown in Libraries.php:503

**Comment by alexbowers** [comment]
Possibly interesting, more infuriating though.

The test passes if we do this:

```php
	public function testDeprectatedInit() {
		include "/var/www/vhosts/lithium/tests/mocks/core/MockInitMethod.php";
		$this->assertException("/Deprecated/", function() {
			MockInitMethod::li3();
		});
	}
```

**Comment by alexbowers** [comment]
I give up. I cant get any further than this:

```
php: /home/vagrant/php-src/Zend/zend_execute.c:2466: cleanup_unfinished_calls: Assertion `op_num' failed.
Aborted (core dumped)
```

And I also cannot get any core dump files to be read. gdb does not like the generated files.

Hacky fix acceptable?

**Comment by alexbowers** [comment]
Nevermind. The hacky fix gets rid of the seg fault, but the test fails. It does not throw the exception.

**Comment by alexbowers** [comment]
Bug filed with PHP https://bugs.php.net/bug.php?id=71163

**Comment by alexbowers** [comment]
Fixed on 7.0.2 (Release expected Jan 2016) https://github.com/php/php-src/commit/eb4ce3f1a8d3c14bf9245ef730d885be359499a8

**Comment by alexbowers** [comment]
![image](https://cloud.githubusercontent.com/assets/842974/11912591/a6e09c22-a63b-11e5-9565-068275b4486e.png)

**Comment by nateabele** [comment]
Nice.

**Comment by alexbowers** [comment]
@nateabele Issue can be closed since it is fixed in the next version of PHP (7.0.2)

**Comment by davidpersson** [comment]
@alexbowers Thanks for investigating and filing the bug over at php.net

**Comment by shopblocks** [comment]
http://www.php.net/ChangeLog-7.php#7.0.2

This has now been put live.
