### ISSUE TITLE
[PHP 7 Failing Test] Var export circular reference 2

### ISSUE THREAD

**Issue by alexbowers** [UnionOfRAD/lithium#1241]
ErrorException (E_WARNING) thrown.
 File    : /var/www/vhosts/lithium/test/Unit.php
 Class   : lithium\test\Unit
 Method  : lithium\test\{closure}()
 Line    : 1872
 ________
var_export does not handle circular references
 ________
var_export, line ??
lithium\test\Unit::_message(), line 1872
lithium\test\Unit::assert(), line 237
lithium\test\Unit::assertArrayHasKey(), line 957
lithium\tests\cases\test\MockerTest::testMagicCallGetStoredResultsWhenCalledIndirectly(), line 436
lithium\test\Unit::lithium\test\{closure}() @ ?, line 1611
lithium\core\Object::_filter(), line 263
lithium\test\Unit::_runTestMethod(), line 1615
lithium\test\Unit::run(), line 213
lithium\util\Collection::invoke(), line 193
lithium\util\Collection::__call(), line 207
lithium\test\Report::run(), line 147
lithium\test\Dispatcher::run()::{closure} @ 65, line 69
lithium\core\StaticObject::_filter(), line 140
lithium\test\Dispatcher::run(), line 73
lithium\console\command\Test::run()::{closure} @ 235, line 236
lithium\console\command\Test::lithium\console\command\{closure}() @ ?, line 145
lithium\console\command\Test::run(), line 238
lithium\core\Object::invokeMethod(), line 179
lithium\console\Command::__invoke(), line 139
lithium\console\Dispatcher::lithium\console\{closure}() @ ?, line 198
lithium\core\StaticObject::_filter(), line 140
lithium\console\Dispatcher::_call(), line 201
lithium\core\StaticObject::invokeMethod(), line 84
lithium\console\Dispatcher::run()::{closure} @ 95, line 105
lithium\core\StaticObject::_filter(), line 140
lithium\console\Dispatcher::run(), line 109
/var/www/vhosts/lithium/console/lithium.php::{closure} @ 74, line 75
[main], line 110
 ________

**Comment by davidpersson** [comment]
Closing in favor of #1240
