### ISSUE TITLE
[PHP 7 Failing Test] Undefined Variable expected but not thrown

### ISSUE THREAD

**Issue by alexbowers** [UnionOfRAD/lithium#1242]
Failed assertion assertException.
 File    : /var/www/vhosts/lithium/tests/cases/template/view/adapter/FileTest.php
 Class   : lithium\tests\cases\template\view\adapter\FileTest
 Method  : testRenderingWithNoExtraction()
 Line    : 48
 ________
An exception "Undefined variable: foo" was expected but not thrown.

**Comment by davidpersson** [comment]
Fixed by fd27fcd, see commit message for reason.
