### ISSUE TITLE
Failing Test ContextText 301

### ISSUE THREAD

**Issue by alexbowers** [UnionOfRAD/lithium#1244]
Failed assertion assertPattern.
 File    : /var/www/vhosts/lithium/tests/cases/net/socket/ContextTest.php
 Class   : lithium\tests\cases\net\socket\ContextTest
 Method  : testContextAdapter()
 Line    : 178
 ________
expected: '/<title[^>]*>301 Moved<\\/title>/im'
result: '<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en-GB"><head><meta content="text/html; charset=UTF-8"

...

**Comment by davidpersson** [comment]
This was actually a problem with mocker's overwrite functions (not just on PHP7). The problem was only visible when running both cases and integrations in one go. Thanks for reporting. Fixed by 581bde2.
