### ISSUE TITLE
Failing locale tests

### ISSUE THREAD

**Issue by alexbowers** [UnionOfRAD/lithium#1245]
Failed assertion assertEqual.
 File    : /var/www/vhosts/lithium/tests/cases/g11n/LocaleTest.php
 Class   : lithium\tests\cases\g11n\LocaleTest
 Method  : testPreferredFromConsoleRequestLcAll()
 Line    : 274
 ________
expected: 'es_ES'
result: 'en_US'

Failed assertion assertEqual.
 File    : /var/www/vhosts/lithium/tests/cases/g11n/LocaleTest.php
 Class   : lithium\tests\cases\g11n\LocaleTest
 Method  : testPreferredFromConsoleRequestPrecedence()
 Line    : 312
 ________
expected: 'fr_CA'
result: 'en_US'

**Comment by davidpersson** [comment]
This does not fail on travis or my environment. Please check if a more recent PHP 7 version fixes this.

**Comment by alexbowers** [comment]
Locally for myself, it appears that in PHP 5.6 LANGUAGE (as an env) is set to en_US in the following tests:

- testPreferredFromConsoleRequestLcAll
- testPreferredFromConsoleRequestPrecedence

In the initialisation of these requests, adding `'LANGUAGE' => null` makes the tests pass in both PHP 5.6 and PHP 7 for myself.

I am unsure what the meaning of this is, or where LANGUAGE gets set.

Could it perhaps be obtained from my command line tool (iterm)

**Comment by davidpersson** [comment]
Aaah. The tests were not properly isolated. See if the commit b54c770 fixes the problem for you. Thanks for reporting and investigating!

**Comment by alexbowers** [comment]
Confirmed Fixed.

**Comment by davidpersson** [comment]
:tada:
