### ISSUE TITLE
[PHP 7 Failing Test] Locale Test 2

### ISSUE THREAD

**Issue by alexbowers** [UnionOfRAD/lithium#1246]
Failed assertion assertEqual.
 File    : /var/www/vhosts/lithium/tests/cases/g11n/LocaleTest.php
 Class   : lithium\tests\cases\g11n\LocaleTest
 Method  : testPreferredFromConsoleRequestPrecedence()
 Line    : 312
 ________
expected: 'fr_CA'
result: 'en_US'

**Comment by davidpersson** [comment]
Closing in favor of #1245
