### ISSUE TITLE
Failing iconv tests

### ISSUE THREAD

**Issue by alexbowers** [UnionOfRAD/lithium#1247]
Failed assertion assertException.
 File    : /var/www/vhosts/lithium/tests/cases/g11n/multibyte/adapter/IconvTest.php
 Class   : lithium\tests\cases\g11n\multibyte\adapter\IconvTest
 Method  : testStrlenInvalidTriggersError()
 Line    : 77
 ________
An exception "/Detected an incomplete multibyte character in input string/" was expected but not thrown.

Failed assertion assertException.
 File    : /var/www/vhosts/lithium/tests/cases/g11n/multibyte/adapter/IconvTest.php
 Class   : lithium\tests\cases\g11n\multibyte\adapter\IconvTest
 Method  : testStrposTriggersError()
 Line    : 137
 ________
An exception "/Detected an illegal character in input string/" was expected but not thrown.

Failed assertion assertException.
 File    : /var/www/vhosts/lithium/tests/cases/g11n/multibyte/adapter/IconvTest.php
 Class   : lithium\tests\cases\g11n\multibyte\adapter\IconvTest
 Method  : testSubstrInvalidTriggersError()
 Line    : 239
 ________
An exception "/Detected an illegal character in input string/" was expected but not thrown.

**Comment by davidpersson** [comment]
Please post the output of the following command (I suspect this being a library version problem):
`php -i | grep '^iconv'`

I'm running the following command and all seems green. I'm using this VM:https://github.com/rlerdorf/php7dev

`console/li3 test tests/cases/g11n/`

**Comment by alexbowers** [comment]
![image](https://cloud.githubusercontent.com/assets/842974/12075618/94c5cb96-b17d-11e5-8551-424b36d20552.png)

**Comment by alexbowers** [comment]
```
----
Test
----

............................................................
..................F.....F...................................
............................................................
............................................................
............................................................
...................F......F......F....FSS...................
....SSSSSSSSSSSSSSS..S

FAIL

358 / 364 passes
6 fails and 0 exceptions

Failed assertion assertEqual.
 File    : /var/www/vhosts/lithium/tests/cases/g11n/LocaleTest.php
 Class   : lithium\tests\cases\g11n\LocaleTest
 Method  : testPreferredFromConsoleRequestLcAll()
 Line    : 274
 ________
expected: 'es_ES'
result: 'en_US'

 ________

Failed assertion assertEqual.
 File    : /var/www/vhosts/lithium/tests/cases/g11n/LocaleTest.php
 Class   : lithium\tests\cases\g11n\LocaleTest
 Method  : testPreferredFromConsoleRequestPrecedence()
 Line    : 312
 ________
expected: 'fr_CA'
result: 'en_US'

 ________

Failed assertion assertException.
 File    : /var/www/vhosts/lithium/tests/cases/g11n/multibyte/adapter/IconvTest.php
 Class   : lithium\tests\cases\g11n\multibyte\adapter\IconvTest
 Method  : testStrlenInvalidTriggersError()
 Line    : 77
 ________
An exception "/Detected an incomplete multibyte character in input string/" was expected but not thrown.
 ________

Failed assertion assertException.
 File    : /var/www/vhosts/lithium/tests/cases/g11n/multibyte/adapter/IconvTest.php
 Class   : lithium\tests\cases\g11n\multibyte\adapter\IconvTest
 Method  : testStrposTriggersError()
 Line    : 137
 ________
An exception "/Detected an illegal character in input string/" was expected but not thrown.
 ________

Failed assertion assertException.
 File    : /var/www/vhosts/lithium/tests/cases/g11n/multibyte/adapter/IconvTest.php
 Class   : lithium\tests\cases\g11n\multibyte\adapter\IconvTest
 Method  : testStrrposTriggersError()
 Line    : 195
 ________
An exception "/Detected an illegal character in input string/" was expected but not thrown.
 ________

Failed assertion assertException.
 File    : /var/www/vhosts/lithium/tests/cases/g11n/multibyte/adapter/IconvTest.php
 Class   : lithium\tests\cases\g11n\multibyte\adapter\IconvTest
 Method  : testSubstrInvalidTriggersError()
 Line    : 239
 ________
An exception "/Detected an illegal character in input string/" was expected but not thrown.
 ________



```

**Comment by alexbowers** [comment]
This is on a php version built from source.

**Comment by davidpersson** [comment]
Try switching to 7.0.3-dev than and rebuild so you get the latest version (there have been some fixes since mid december). 

```
newphp 70
makephp 7
```

Also the travis env seems to not have these issues, too.

**Comment by alexbowers** [comment]
Im happy to say they dont exist if you cannot replicate, since I cannot get beyond 7.0.1 currently (using a PPA), and the next upgrade to 7.0.2 is in mid-january i believe.

Failing that, I am happy to return to this issue when 7.0.2 has been released.

**Comment by davidpersson** [comment]
I seem to have the same iconv and don't see the errors - which does not mean there isn't a problem. Can you check your error level with `php -i | grep error_reporting`? it should be `-1`.

**Comment by davidpersson** [comment]
Fixed by fd27fcd, see commit message for reason.

**Comment by alexbowers** [comment]
![image](https://cloud.githubusercontent.com/assets/842974/12079703/e93bdec8-b23a-11e5-97a9-598d617cfc05.png)

**Comment by alexbowers** [comment]
And you were correct with the error reporting, mine was completely wrong (based on default setup).

![image](https://cloud.githubusercontent.com/assets/842974/12079706/0ee1bd3c-b23b-11e5-8500-18b9a9ec033b.png)
