### ISSUE TITLE
[PHP 7 Failing Test] Illegal character in input string

### ISSUE THREAD

**Issue by alexbowers** [UnionOfRAD/lithium#1248]
Failed assertion assertException.
 File    : /var/www/vhosts/lithium/tests/cases/g11n/multibyte/adapter/IconvTest.php
 Class   : lithium\tests\cases\g11n\multibyte\adapter\IconvTest
 Method  : testStrposTriggersError()
 Line    : 137
 ________
An exception "/Detected an illegal character in input string/" was expected but not thrown.

**Comment by davidpersson** [comment]
Closed in favor of #1247
