### ISSUE TITLE
[PHP 7 Failing Test] Undefined Offset

### ISSUE THREAD

**Issue by alexbowers** [UnionOfRAD/lithium#1250]
Failed assertion assertException.
 File    : /var/www/vhosts/lithium/tests/cases/data/source/DatabaseTest.php
 Class   : lithium\tests\cases\data\source\DatabaseTest
 Method  : testCalculation()
 Line    : 519
 ________
An exception "Undefined offset: 0" was expected but not thrown.

**Comment by davidpersson** [comment]
Fixed by fd27fcd, see commit message for reason.
