### ISSUE TITLE
[RFC] Policy change on Copyright Notices

### ISSUE THREAD

**Issue by alexbowers** [UnionOfRAD/lithium#1254]
Currently, the copyright on all files is updated each year, so that we would have it set to the current year.

This seems strange, since licenses and copyright is from when the work was first produced and copy-written .

Since this is a change in policy an RFC is opened.

**Comment by Filisko** [comment]
Well... I don't know too much about this, but have a look to GitHub's, why do you think that they update it?

I think that we should always update it, just in case.

**Comment by davidpersson** [comment]
@Filisko A website's footer (like GitHub's) is something different. Usually companies like to indicate that the website is current.

Go and Apache Mesos don't update the Copyright year. The copyright year is determined by when the file was created. The reason behind this is, that given a project isn't updated for over a year, a year update commit must still occur. As each commit would require a (patch) release this does not make much sense.

https://github.com/golang/go/blob/master/src/os/dir_unix.go

**Comment by davidpersson** [comment]
At this point we can't go back to my suggestion in the last comment. Let's keep it as is.
