### ISSUE TITLE
String::compare is not constant-time

### ISSUE THREAD

**Issue by nanobe** [UnionOfRAD/lithium#1259]
String::compare is documented as a constant-time string comparison function, but it actually leaks timing information in the character-by-character comparison loop.

The line "$result = $result && ($known[$i] === $user[$i]);" uses a logical "and", which means if the first comparison ("$result") is false, then the second comparison won't be evaluated. In other words, the loop is sped up after the first mismatched character, which means the overall string comparison completes sooner the earlier it finds a mismatched character. This is exactly what you don't want to have happen.

Since logical "and" and "or" operators can short-circuit depending on the result of the first comparison, constant-time string comparison functions usually rely on bitwise operations instead. For example, you can compare two characters by doing a bitwise "xor" on their numeric byte values (resulting in 0 if they are equal) and accumulate any resulting errors into an integer result variable using a bitwise "or". If that result variable is still equal to 0 in the end, the strings are equal.

**Comment by nateabele** [comment]
So, flipping the order of the comparison should work then, yeah?

**Comment by nateabele** [comment]
Alternatively, we could drop it: https://secure.php.net/manual/en/function.hash-equals.php

**Comment by davidpersson** [comment]
I'm on it and will push/release a solution for v0.11.1 v1.0.0-rc3 and v1.1.x.

**Comment by nanobe** [comment]
nateabele: Flipping the order wouldn't be enough. In that case, the loop would only check the value of $result when there's a mismatched character, meaning the overall function completes faster the more characters are correct. That's also not desirable.

davidpersson's changes look good to me.

**Comment by alexbowers** [comment]
Comment left on the commit. but [ord](http://php.net/manual/en/function.ord.php) is not compatible with UTF8, so perhaps it isn't an ideal check?

**Comment by alexbowers** [comment]
For example, i'm going to use the characters: 'Ð' and 'Â'

ord() returns them both as int(195)

strlen returns them both as having length of 2.

Doing a foreach over the length on that returns null for the character since there is no character at the position (it has two character positions).

Fixing the function to report the string lengths properly (mb_strlen instead of strlen), shows the true bug here though: ord considers those characters to be the same:

https://3v4l.org/vnvpc

The original returned false, so looks like it works, but i do not think it is safe, since it doesn't compare the strings properly.

**Comment by alexbowers** [comment]
Interestingly, PHP behaves differently as well based on the versions as seen in the above link.

**Comment by nanobe** [comment]
alexbowers: ord is compatible with UTF-8, but in the sense that you get the value of an individual byte rather than the codepoint of a Unicode character. For cryptographic purposes, you usually want to operate on a byte level anyway.

**Comment by alexbowers** [comment]
@nanobe Unfortunately, this produces the same character code for two characters, and considers them the same (if using mb_strlen).

**Comment by davidpersson** [comment]
If you switch mb_strlen to strlen (which is what the patch uses) it has correct results.

**Comment by nanobe** [comment]
@alexbowers I think the reason the result of your test varied by PHP version was because you didn't explicitly specify which encoding to use. If you put 'UTF-8' in the second parameter of your mb_strlen functions, the results become consistent.

But still, when you're doing this kind of work, you want to operate on a byte-by-byte level, not a character-by-character level. Not all streams of bytes properly map to UTF-8 characters, and those bytes could end up getting silently replaced with something else (0xfffd, ?, or empty string depending on how the UTF-8 function you're using decides to handle them). Interpreting an arbitrary byte stream as UTF-8 is a lossy operation, but all UTF-8 streams can be unambiguously processed as a stream of bytes. You just have to keep in mind that a "character" might consist of any number of bytes.

**Comment by alexbowers** [comment]
Ah okay, that makes sense. Thanks @nanobe

**Comment by davidpersson** [comment]
@nanobe thank you for investigating and verifying the fix. Next time please report security issues to security@li3.me first, before going public. I had to fix this from the edge of my bed... seriously by following  https://github.com/UnionOfRAD/lithium/blob/master/CONTRIBUTING.md you give us more time to find a good fix.

**Comment by davidpersson** [comment]
Release announcements with the fix:
http://news.li3.me/post/137243059563/100-rc4-released
https://twitter.com/UnionOfRAD/status/687400656987107328

**Comment by nanobe** [comment]
@davidpersson Sorry about that. Will do.

**Comment by davidpersson** [comment]
@nanobe No worries, glad that we found and fixed the issue.
