### ISSUE TITLE
Emoji Storage with MySQL

### ISSUE THREAD

**Issue by shopblocks** [UnionOfRAD/lithium#1261]
When trying to store an emoji such as 🌂 in Li3, we get a mysql error about 'Incorrect string value'.

We have set the charsets to utf8mb4, but have the 'Connections::add' with an encoding of UTF-8. We tried changing that to utf8mb4, but that didn't work / fix anything.

Is there a step we are missing, or is this a bug with how Lithium saves?

To prove it works with the character set, we stored it successfully via Adminer into the same database.

**Comment by davidpersson** [comment]
Do all emojis need 4 byte Unicode? Asking because I'm able to store at least some emojis without an error using utf8. I'm on MariaDB 10.1.9.

**Comment by shopblocks** [comment]
Unsure whether they are all 4 byte unicode. The one given above is a 4 byte emoji and it breaks

![image](https://cloud.githubusercontent.com/assets/14819903/12428869/10ed4352-bedf-11e5-9be2-6b50229e67c0.png)

**Comment by davidpersson** [comment]
❤️s seem to work might prove some do not require 4 byte.

**Comment by davidpersson** [comment]
Okay I've found the problem, will provide a fix tomorrow.

**Comment by davidpersson** [comment]
Closed by 102cdc2
