### ISSUE TITLE
Cannot use lithium\util\String as String because 'String' is a special class name in C:\lithium-0.10\libraries\lithium\core\Libraries.php on line 12

### ISSUE THREAD

**Issue by sildeag** [UnionOfRAD/lithium#1267]
Newbie to php.
Anyone know what is causing this problem?
/** line 12 is: use lithium\util\String;  **/
/** Using Windows 10, IIS Express 10, and PHP 7 **/

/** Libraries.php **/
<?php
/**
 * Lithium: the most rad php framework
 *
 * @copyright     Copyright 2011, Union of RAD (http://union-of-rad.org)
 * @license       http://opensource.org/licenses/bsd-license.php The BSD License
 */

namespace lithium\core;

use RuntimeException;
use lithium\util\String;  /** line 12 **/
use lithium\core\ConfigException;
use lithium\core\ClassNotFoundException;

**Comment by nateabele** [comment]
Please check out the 1.1 branch, which has been updated for PHP 7.

**Comment by sildeag** [comment]
Hi Nate,

 

I wasn’t sure exactly how to implement your changes, probably did it wrong, but they worked.  I put your tree into Lithium-0.10/libraries/lithium.  Thanks.

That issue is closed.  The default website was interesting.

 

I was interested in getting MongoDB to work and uncommented the in config\bootstrap and am investigating what below means:

 

Gordon

 

Uncaught lithium\core\ClassNotFoundException: Class `Index.Php` of type `controllers` not found. in C:\lithium-0.10\libraries\lithium\core\Libraries.php:690 Stack trace: #0 C:\lithium-0.10\libraries\lithium\aop\Filters.php(229): lithium\core\Libraries::lithium\core\{closure}(Array) #1 C:\lithium-0.10\libraries\lithium\core\Libraries.php(699): lithium\aop\Filters::run('lithium\\core\\Li...', 'instance', Array, Object(Closure)) #2 C:\lithium-0.10\libraries\lithium\action\Dispatcher.php(251): lithium\core\Libraries::instance('controllers', 'Index.Php', Array) #3 C:\lithium-0.10\libraries\lithium\aop\Filters.php(229): lithium\action\Dispatcher::lithium\action\{closure}(Array) #4 C:\lithium-0.10\libraries\lithium\action\Dispatcher.php(255): lithium\aop\Filters::run('lithium\\action\\...', '_callable', Array, Object(Closure)) #5 C:\lithium-0.10\libraries\lithium\action\Dispatcher.php(167): lithium\action\Dispatcher::_callable(Object(lithium\action\Request), Array, Array) #6 C:\lithium-0.10\libraries\lithium\aop\Cha in C:\lithium-0.10\libraries\lithium\action\Dispatcher.php on line 253

**Comment by davidpersson** [comment]
Please use http://stackoverflow.com/questions/tagged/lithium for support/help questions. Thanks!
