### ISSUE TITLE
FormSignature and saving model

### ISSUE THREAD

**Issue by fancenl** [UnionOfRAD/lithium#1268]
Hey guys,

When I use the FormSignature-feature, an extra hidden field will be added to my form. This is the intention of course. But, when I do:

```
if ($this->request->is('post') && FormSignature::check($this->request)) {
    Clients::update($this->request->data, array('id' => Auth::check('client')['id']));
}
```

the MySQL-adapter returns the following error:

```
UPDATE `clients` SET `firstname` = '', `lastname` = '', `security` = Array WHERE `id` = 18;: Unknown column 'security' in 'field list'
```

In other words; Lithium expects a 'security' field in my database table. How can I exclude this field from saving? Is this a bug or am I doing something wrong?

**Comment by davidpersson** [comment]
For saving data use `Model::save()`:

```
if ($this->request->is('post') && FormSignature::check($this->request)) {
    $client = Clients::create($this->request->data);
    $client->save(array('id' => Auth::check('client)['id']));
}
```

Even better use whitelists and validate before save. `id` should probably be auto incrementing and an extra `user_id` field might be a better choice.

```
if ($this->request->is('post') && FormSignature::check($this->request)) {
    $client = Clients::create($this->request->data);

    if ($client->validates()) {
       $client->save(array('user_id' => Auth::check('client)['id']), array('whitelist' => array('id', 'user_id', 'name', 'email));
    } 
}
```

Please use stackoverflow and tag with "lithium" for support questions.
