### ISSUE TITLE
Legacy mongo vs new mongodb driver implemenation

### ISSUE THREAD

**Issue by fitzagard** [UnionOfRAD/lithium#1269]
Alas, the `mongo` driver used by li3 is now considered [legacy](https://pecl.php.net/package/mongo) and is incompatible with mongod 3.2+. Interestingly, there is now a [php mongo library](https://github.com/mongodb/mongo-php-library) courtesy of the mongodb team providing high-level abstraction. Sorry if I missed the conversation on this but I'm wondering what direction li3 will take with the built-in MongoDB class. Is there an MongoDB overhaul coming or a suggested path to migrate to the new driver with the current li3 1.0 path?

**Comment by davidpersson** [comment]
As 1.0 is still PHP 5.3 and 1.1 is PHP 5.5. 1.1 is the earliest version we'd be able to implement support for the new mongodb ext.

**Comment by davidpersson** [comment]
This should happen in 1.2 as 1.1 already has many changes. It seems like an issue we do not need to solve not now, but somewhat soonish. @fitzagard I'm in favor of switching to the low-level driver/pecl-ext and do not rely on the high-level driver. That might give us higher performance as a reward of going through the refactor. What do you think? Or is the pecl-ext too low level for us?

**Comment by fitzagard** [comment]
@davidpersson I agree, refactoring with the low-level driver could be a better option. It is very "bare metal" and may require a good deal of work to provide palatable functionality beyond the basic CRUD. However, it may yield a cleaner hook into the li3 Document/Model structure and higher performance gains. Anyone needing deeper functionality can include the high-level library which seems robust and easy to integrate. But thats just my cheap 2 cents worth of thoughts 👍

**Comment by davidpersson** [comment]
Supporting the new extension is also required for full PHP7 support, mongo has none.

**Comment by internetstyle** [comment]
+1

**Comment by davidpersson** [comment]
I'll come up with a plan on how to approach this. We'll definitely need help implementing this.

**Comment by ericcholis** [comment]
@davidpersson @fitzagard I'm leaning towards the low-level driver as well. Using the high-level driver for design reference is a good plan of attack. But, the low-level driver should enable us to stick closer to the "li3 way".

**Comment by jails** [comment]
@fitzagard, @davidpersson, @ericcholis I sketched up [the new `MongoDb` class there](https://github.com/UnionOfRAD/lithium/pull/1305). The only drawback is GridFS is not supported by the new mongodb driver out of the box, so I removed GridFS support for now. So I think we will need a plan for what to do next.

**Comment by davidpersson** [comment]
Closing in favor of #1305
