### ISSUE TITLE
Increase minimum PHP version for 1.1 to 5.5.14

### ISSUE THREAD

**Issue by vbresults** [UnionOfRAD/lithium#1271]
With the new filter implementation and removal of $self, 1.1.x is affected by https://bugs.php.net/66622

If you are running anything older than 5.5.14 models filters and anything else that uses late static binding in filters is busted.

**Comment by davidpersson** [comment]
Thanks for reporting. Fixed in b4f626eb3d4cf269196d086886b8c9a237749f75.
