### ISSUE TITLE
Provide autoBind option to bind filter functions to context

### ISSUE THREAD

**Issue by vbresults** [UnionOfRAD/lithium#1272]
The deprecated notice on the old filter implementation says to use static:: instead of $self, since that is now gone, but the filter closures are never bound to the static class in question.

So, then, the class referred to in static:: ends up being `lithium\core\Libraries` or nothing, completely ignoring the correct static class/context.   Ping @jperras @davidpersson @nateabele @gwoo

**Comment by davidpersson** [comment]
Thanks for submitting this report. Can you paste the exact error message and context the error is triggered in?

**Comment by vbresults** [comment]
`PHP Fatal error:  Call to undefined method lithium\core\Libraries::read() in /var/www/com.vbresults.apps.ci/libraries/xxx/config/bootstrap/yyy.php on line ...`

```PHP
use lithium\aop\Filters;

Filters::apply('app\extensions\adapter\Zzz', 'delete', function($params, $next) {
	foreach ($params['profiles'] as $profile):
		if (!($file = static::read(compact("profile")))):
			continue;
		endif;

		unlink($file);
	endforeach;

	return $next($params);
});
```

PHP `5.6.11`

**Comment by davidpersson** [comment]
app\extensions\adapter\Aaa::read() is static or concrete?

**Comment by vbresults** [comment]
Right, static

**Comment by davidpersson** [comment]
`Filters` will not auto-bind context of the filters (closures). This is i.e. because filters can originate from a static method and target a concrete method. This also fits well with our no automagic approach.

In your case you should use the (fully classified) class name instead of "static" - as you create the filter outside any class scope (in bootstrap phase I persume):

```
Filters::apply('app\extensions\adapter\Aaa', 'delete', function($params, $next) {
    foreach ($params['profiles'] as $profile):
        if (!($file = \app\extensions\adapter\Aaa::read(compact("profile")))):
            continue;
        endif;

        unlink($file);
    endforeach;

    return $next($params);
});
```

**Comment by vbresults** [comment]
@davidpersson This isn't an adequate replacement for the removed $self variable -- at the very least, can the Filters class be configured with an option to auto-bind?  Something like `\lithium\aop\Filters::config("default", Filters::config("default") + array('auto_bind' => true));`

**Comment by davidpersson** [comment]
The documentation (manual) will be updated. 
I'll look into if auto-binding is feasible, if not will document the why not.

**Comment by davidpersson** [comment]
@vbresults Meanwhile this might work:
```
Filters::apply('app\extensions\adapter\Aaa', 'delete', function($params, $next) {
    // ...
        if (!($file = static::read(compact("profile")))):
    // ...
    return $next($params);
}->bindTo(null, '\app\extensions\adapter\Aaa'));
```

**Comment by vbresults** [comment]
That's what I started doing when I initially reported this but it looks so ugly :(

Then I have to do the same thing for all of the use() functions too

**Comment by blubear83** [comment]
@vbresults why not extend Filters class, add the auto binding function and use it until it gets added to the core Filters class. If it doesn't get added, it'd still work for your purpose.

**Comment by vbresults** [comment]
This is the way I ended up going, which in retrospect, is the correct way to do it:
```
use app\extensions\adapter\Aaa;

Filters::apply(Aaa::class, 'delete', function($params, $next) {
    // ...
        if (!($file = Aaa::read(compact("profile")))):
    // ...
    return $next($params);
});
```

**Comment by davidpersson** [comment]
Great, you've found such an obvious solution for this. Strange is I didn't ;)
