### ISSUE TITLE
Database connection to mysql does use unix_socket options

### ISSUE THREAD

**Issue by josh4trunks** [UnionOfRAD/lithium#1273]
This below block has a few issues.
https://github.com/UnionOfRAD/lithium/blob/master/data/source/database/adapter/MySql.php#L159-163

It looks like it's trying to split host (i.e. host = localhost:/tmp/mysql.sock) while `data/Connections.php` says to pass your parameters as host, port, socket. In reality PDO expects unix_socket.

I think the best solution is to not even do the explode, and just pass host/port/unix_socket as (somewhat) documented.

**Comment by davidpersson** [comment]
> I see multiple problems here, we have to resolve this in a broader scope. Connections::add should not know about host, login, password, but subclasses of Source should handle this. Users should be able to go to the API docs of their driver class and there see any required/optional settings. DSN is an internal implementation detail. unix_socket should be supported through a socket config setting. We should also deprecate usage of : notation in all Database subclasses.

**Comment by davidpersson** [comment]
With the existing code does passing a socket path in `'host'` work for you?

**Comment by josh4trunks** [comment]
I'll test if host:port or host:socket works. if that's how you prefer it be done I can refacture the code. that's how i've help implement it before in owncloud.

but I doubt it will works from looking at how this passes parameter to PDO
also why is 3306 even there? just dont pass a port if you dont know it

**Comment by josh4trunks** [comment]
@davidpersson Do you prefer things are passed as **host:socket** / **host:port**?

Here's the logic used in owncloud, since ctype digit might not be available we can use the slightly less efficient is_numeric().
https://github.com/owncloud/core/blob/master/lib/private/DB/ConnectionFactory.php#L159-170

**Comment by josh4trunks** [comment]
@davidpersson does not work with the existing code.
`'host'       => localhost:/mnt/mysql/mysql.sock,`

What was wrong with the PR I created? As far as I can understand it does implement what you were saying? Maybe you want the logic in a different file, or additional documentation?

**Comment by davidpersson** [comment]
Thanks for testing and providing more information

Regarding the PR: This needs to be solved not only in MySql but in other data sources and all other classes taking host and socket. As this became more of framework wide conceptual decision I started working on it.

**Comment by josh4trunks** [comment]
Ok, sounds good. Tell me if you need any additional contributions/testing for the mysql driver.

**Comment by davidpersson** [comment]
Fixed in ef9eaee871caf4ec874389b559d8b8c8dda918b2

**Comment by josh4trunks** [comment]
awesome, thanks! I'll test this out when I get a chance.

Should applications no longer use **$port** then and if connecting to a non-default port, have **$host=hostname:port**? I want to make sure nZEDb passes the parameters correctly to lithium.

**Comment by davidpersson** [comment]
Yes there is no separate port option, just host (which takes host and port as `HOST:PORT`).

**Comment by josh4trunks** [comment]
ok, that's what I thought I read. great, thanks
