### ISSUE TITLE
Shorthand RESTful router methods

### ISSUE THREAD

**Issue by fedeisas** [UnionOfRAD/lithium#1275]
Hi! I think that `Router#connect()` could have some aliases to set routes with the correct HTTP method. Something like:

```
class Router
{
    public static function get($template, $params = array(), $options = array())
    {
        return static::connect($template, $params, ['http:method' => 'GET'] + $options);
    }
}
```

**Comment by davidpersson** [comment]
Thanks for submitting the feature request. `Router` already has  a large API surface which I don't want to add more methods to.
