### ISSUE TITLE
1.1: Showstopper: Associated records hydrated out of order

### ISSUE THREAD

**Issue by vbresults** [UnionOfRAD/lithium#1276]
https://github.com/UnionOfRAD/lithium/blob/b8f908123162e19e9989722f0675ab9c7628fd00/data/collection/RecordSet.php#L140

When a `Model::all` call has more than one record, this exception is thrown, and breaks the application.  PHP 5.6.20, MariaDB 5.5.49, php5-mysqlnd.  I am not 100% certain, but I suspect why this is happening:

`list()` (or something similar) was implemented recently somewhere in a PHP 7 context, and PHP 5 and 7 assign variables in opposite orders, so that update broke 1.1 for non-PHP7 installs.

@davidpersson Retagged this as showstopper because it completely stops the application from working

**Comment by davidpersson** [comment]
Thanks for reporting! Can you provide some test data to reproduce the problem? I'd like to clear this up as soon as possible.

**Comment by vbresults** [comment]
`Model::all(['conditions' => ['parent_id' => $auth['id']], 'with' => $this->_with, 'order' => ['created' => "DESC"]]);`

For the primary table:

1x unsigned int primary key
1x unsigned bigint
4x varchar
1x text
2x datetime

This models has a few different relationships:

1x BelongsTo
3x HasMany
1x HasMany.HasMany

**Comment by davidpersson** [comment]
Please see https://github.com/UnionOfRAD/lithium/blob/1.1/CHANGELOG.md#fixed-1 under "Fixed undetected buggy behavior in ..." and try the following:

```
// Assuming your Main model is Foos and in the with clause is Bars
Foos::find('all', array(
  'conditions  => array('parent_id' => 23),
  'order' => array(
    'id', // needed here
    'Foos.created' => 'DESC' // better qualify this to make it unambiguous 
  ),
  'with' => 'Bars'
));
```

Caching should not be the cause here. I think it was the unclear usage (see above).

**Comment by vbresults** [comment]
In the actual implementation, created is qualified (actually, it's a relation `created` field that I'm sorting by), but I was not using `id` for sure; thank you for the resolution

**Comment by davidpersson** [comment]
I've created an issue in the manual as we need to document this.

**Comment by vbresults** [comment]
@davidpersson When I use this, ordering by the rest of the fields does not work, so it completely breaks the 'order' functionality.  I think something is fundamentally wrong with the hydration method

**Comment by davidpersson** [comment]
Order by related fields first is not supported (also not in other ORMs like i.e. CakePHP's). You must order by main model fields first. If you've been thinking that this was possible, than this is clearly a documentation issue which we will need to solve.

**Comment by vbresults** [comment]
The problem I was experiencing was due to an error I made (confusing `'order' => ["Primary.id", ["Secondary.created" => "DESC]` and `'order' => ["Primary.id", "Secondary.created" => "DESC`)
