### ISSUE TITLE
Mongo queries always read from Primary despite Connections::add() readPreference config

### ISSUE THREAD

**Issue by fitzagard** [UnionOfRAD/lithium#1279]
When setting up Connections::add() I specified the readPreference as MongoClient::RP_SECONDARY. 

Tracing it through that allows the server configuration to be properly setup in [the MongoDB Class](https://github.com/UnionOfRAD/lithium/blob/1.0/data/source/MongoDb.php#L316):

`$this->server->setReadPreference($prefs[0], $prefs[1]);` 

However, come connection and query time my reads were going to the Primary. So I took a closer look at:

`$collection = $self->connection->{$source}` in [MongoDb::read()](https://github.com/UnionOfRAD/lithium/blob/1.0/data/source/MongoDb.php#L539)

$self contains the correct readPreference of `secondary` however $self->connection is set to `primary`. So no matter what is specified in Connection:add() the mongoDB Primary will always be queried. That said, should the readPreference be set on $this->connection? Or is there a problem with the Mongo PHP driver inheritance scheme? Or, am I missing something?

**Comment by davidpersson** [comment]
As per https://derickrethans.nl/readpreferences.html

> It is also possible to set the Read Preference on a connection, database or collection object. When a read preference is set, it is inherited by every database or connection object that is created afterwards:

...it seems the problem here is that we set the read preference on the client after we establish the connection.

**Comment by fitzagard** [comment]
It also looks like applying the readPreference to connection (instead of server) offers more flexibility. Then before running a query one could change the read through `Model::connection()->setReadPreference()`

**Comment by davidpersson** [comment]
So instead applying it to the client we'll set it on the connection. I like the idea.

**Comment by davidpersson** [comment]
@fitzagard Wouldn't changing the read preference afterwards via `Model::connection()->setReadPreference()` be possible even if we had set it on the client? If that's possible I'd be in favor of setting it on the client, as that doesn't change behavior (who knows what else depends on this) and just fixes the bug.

**Comment by fitzagard** [comment]
@davidpersson After a bit more investigation it seems like keeping the read preference on the client and using `Model::connection()->_config['readPreference'] = MongoClient::RP_TYPE` will work (the aforementioned Model::connection()->setReadPreference() doesn't work). 

So the setting of the readPreference before the connection is made would be the only change needed to fix the bug.

**Comment by davidpersson** [comment]
Testing goals would be:
1. verify RP was set on server 
2. verify that when set on server PR is propagated to connection: setRP on server must happen before $this->server->DATABASE is accessed

A place for these tests is `tests/mocks/data/source/MockMongoConnection.php` using `tests/cases/data/source/MongoDbTest.php`. The tests might need different setup and the mock might need additional methods/properties to retrieve order in which methods were called.

**Comment by davidpersson** [comment]
@fitzagard Are you working/want to work on tests for this issue? Just asking as you have the most insight into this. In case there currently is no time, that's not a problem. Than somebody else can create the tests/patch. I'd like to get this into the next 1.0.x release.

**Comment by fitzagard** [comment]
@davidpersson I started working on the test for this issue but ran into a snag (then my time got eaten up). The patch seemed straight forward but the tests were giving me trouble to set it up in a manner that properly emulated the mongodb connection/server inheritance structure. I could use some help. I'll push up what I have thus far in my branch. Maybe with a quick peek someone could see where im going wrong.

**Comment by davidpersson** [comment]
Sounds good, just point me to the branch.

**Comment by fitzagard** [comment]
@davidpersson here is where i've been tinkering with the readPref test: https://github.com/UnionOfRAD/lithium/commit/f8f186512f58b3f380d77ea1bb38535f6c9838f0

**Comment by davidpersson** [comment]
Fixed in https://github.com/davidpersson/lithium/commit/62cffc1a18da49e138b5dcafbff9c80ee9b1d677. I've added naive tracing to the already existing MockCallable. This did the job in determining order of database access and setReadPref call. Thanks for working with me on this.

**Comment by fitzagard** [comment]
Looks great. Thanks for clearing up the test. I learned quite a bit from that commit.
