### ISSUE TITLE
Lithium 1.1 throws "MongoClient class not found" exception when calling   \lithium\data\Connections::add(self::MYSQL_WEBSTORE, self::$mysql_webstore);

### ISSUE THREAD

**Issue by nguyener** [UnionOfRAD/lithium#1283]
I ported my web server to php 7 this week.  Since Lithium 1.0 is not compatible with php7, I replaced it with lithium package 1.1.  Whenever I launched a browser to connect to my web server, I got "MongoClient Class Not Found" exception.  

I have my mongo package install on my server correctly

root@6957a861fd23:/# apt-cache search php-mongo
php-mongodb - MongoDB driver for PHP
php-mongo - MongoDB database driver

root@b1692d5b146e:/# php -i | grep mongo
mongodb
mongodb support => enabled
mongodb version => 1.1.7
mongodb stability => stable
libmongoc version => 1.3.5
mongodb.debug => no value => no value

My php server is running on ubuntu16.04 docker container

**Comment by nguyener** [comment]
Btw, no mongo is found when I run phpinfo() script

**Comment by davidpersson** [comment]
We do not yet support the newer `mongodb` extension. You must use the "older" `mongo` extension.
When installed correctly the output of `php -i | grep mongo` should look like:
```
mongo
mongo.allow_empty_keys => 0 => 0
mongo.chunk_size => 261120 => 261120
mongo.cmd => $ => $
mongo.default_host => localhost => localhost
mongo.default_port => 27017 => 27017
mongo.is_master_interval => 15 => 15
mongo.long_as_object => 0 => 0
mongo.native_long => 1 => 1
mongo.ping_interval => 5 => 5
``` 

From the output you posted it seems the `mongo` is either not installed or enabled. For this please search help on stackoverflow or PHP/mongodb related forums.

As this is a problem with the server setup and not a framework issue, I'm closing this now.

**Comment by nguyener** [comment]
Hi David,
I have been searching around and people said legacy mongo does not work with PHP 7.  Could you point me to link(s) on how to install legacy mongo?

**Comment by davidpersson** [comment]
Hi, thanks for pointing this out. I was believing the legacy mongo ext had PHP 7 support. 
So in order to use lithium with MongoDB and PHP7 you'll unfortunately have to wait until we build in support for the new mongodb extension. Please see 1269 for progress on that. Considering we want 1.1 to be PHP7 compatible I might need to reconsider the integration point for it.

**Comment by davidpersson** [comment]
Just found out about this shim https://github.com/alcaeus/mongo-php-adapter - unsure this will work out of the box.
