### ISSUE TITLE
Issues with PHP 7 Support

### ISSUE THREAD

**Issue by ladland** [UnionOfRAD/lithium#1284]
### Unable to run using PHP 7

To support PHP 7 `lithium\util\String` needs to be changed to `lithium\util\LIString` or similar as String is now a reserved keyword and can't be used as a class name due to type support.

I have tested this with an internal instance and it runs without issues.

**Comment by shopblocks** [comment]
Version 1.1 will support PHP 7, and has this change already made.

**Comment by davidpersson** [comment]
Hi @ladland thanks for submitting the PR, (un)fortunately we've already renamed the string class in the 1.1 development branch. There will be no PHP7 support for 1.0. 1.1 will be fully PHP7 compatible. 

You can always ping us on twitter (unionofrad) or mail me directly if you plan to submit a bigger patch.
