### ISSUE TITLE
Filters in lithium 1.1 not working

### ISSUE THREAD

**Issue by shopblocks** [UnionOfRAD/lithium#1286]
After updating lithium to use v1.1 alongside PHP v7, when trying to use the new filters a `DispatchException` is thrown. The call used to look like this:

```PHP
Dispatcher::applyFilter('run', function($self, $params, $chain) {
    ...
    return $chain->next($self, $params, $chain);
}
```

The above code still works, although it does trigger a few warnings. When trying to use the new Filter code like so:

```PHP
Filters::apply('Dispatcher', 'run', function($params, $next) {
    ...
    return $next($params);
}
``` 
The above mentioned `DispatchException` is thrown. Do you have any idea what could be causing this?

**Comment by davidpersson** [comment]
You need to provide the fully namespaced class name:
http://li3.me/docs/api/lithium/1.1.x/lithium/aop/Filters::apply()
