### ISSUE TITLE
Count should not use 'order'

### ISSUE THREAD

**Issue by shopblocks** [UnionOfRAD/lithium#1287]
Currently, a count ignores fields, since it doesn't matter. An order also doesn't matter for a count, so should this not be ignored also?

**Comment by davidpersson** [comment]
Thank you for the suggestion. The framework does deliberately _not_ perform any query optimization. This is to put as much control as possible into the hands of the developer. `count` does not ignore fields, it uses them to build the `COUNT(fields)` part.

**Comment by shopblocks** [comment]
Passing `fields` into `Model::find('count', $params);` gives us `SELECT COUNT(*) ...`

**Comment by davidpersson** [comment]
Passing one field in `'field'` will use that field for counting, passing more than one will do `'*'`.

**Comment by shopblocks** [comment]
Ah okay, thanks for clarification.

**Comment by davidpersson** [comment]
I'll amend the documentation to clarify this.
