### ISSUE TITLE
Proposal: Separation of Views and Default Translation Text

### ISSUE THREAD

**Issue by vbresults** [UnionOfRAD/lithium#1289]
I get a bad feeling in my stomach when I see this pattern in my views:
```PHP
<div><?=$t("Lithium sucks less.  Expand your programming mind.");?></div>
```
Having a copy of text in these templates makes them hard to manage and honestly, I feel it all around sucks.  IMO, an approach more like [Android's](https://developer.android.com/guide/topics/resources/string-resource.html) is correct:
```PHP
<div><?=t(@pages_view_headline);?></div>
```
-  Avoid ugly quotes and undefined constant errors with `@`
-  Naming convention: `prefix`\_`view`\_`key`
- `t()` is enabled via a `Catalog/Message::config` option (off by default to prevent collisions), picked up by IDE, and available everywhere (incl. controllers) without `use lithium\g11n\Message;`

`app/resources/values/strings.xml`
```XML
<?xml version="1.0" encoding="utf-8"?>
<resources>
	<string name="pages_view_headline">Lithium sucks less.  Expand your programming mind.</string>
</resources>
```
I'll be implementing this on my own, and if feedback points to this being eligible for a pull request, then I'll make it when the implementation is complete and tested; thoughts @davidpersson ?

**Comment by davidpersson** [comment]
You are talking about three topics here, these can be decoupled: 
1. symbols as message ids
2. using constants (or some other syntax) for message ids
3. having an XML format holding/mapping message ids to translations

Using symbols as the message id, already works with the current system. You are practically free to use anything as the id you want. Gettext assumes this is the default text. I still think this is a good approach which should be recommended by default. 

The [Globalization Spec](http://li3.me/docs/book/specs/1.x/draft/globalization#best-practices) (which led to the implementation of the current g11n system) does not list _symbols as message ids_ as a best practive. I - however - cannot give you the source where this is coming from.

I would not go as far as saying your approach is more correct than the current one. Use whatever you feel is correct. The framework is flexible enough to cover both approaches.

I don't especially like the use of constants in this, but that might be just my taste.

Regarding the translations file format: If you go with an XML format, I'd suggest to consider using [XLIFF](https://en.wikipedia.org/wiki/XLIFF) as this is already standarized and there is tooling around it. An XLIFF parser/encoder vis a vis the [catalog gettext adapter](https://github.com/UnionOfRAD/lithium/blob/master/g11n/catalog/adapter/Gettext.php) would be of interest. Although I would like to see it prove itself as a plugin with the option of integrating it at a later point (i.e. 2.0) into the core g11n system. 

Thank you for the proposal. Please ping me if you created the implementation as the plugin, so I can review and track the progress on it.

P.s.: There are two different other plugins (li3_lldr and li3_cldr) which do advanced g11n outside of the core.

**Comment by vbresults** [comment]
@davidpersson Thank you for your detailed response; I can see where you are coming from in regards to using constants as symbol ids.  Maybe this type of symbol id is better:
```PHP
<div><?=t("Pages: View Headline");?></div>
```
I feel XLIFF is too complex for my needs, and not aesthetic either.  Logic should be left in the application.  If I skip the unnecessary plurals system, the Android XML format is dead simple to implement.
