### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by aaron50x** [UnionOfRAD/lithium#1290]
I'd like to contribute to this awesome project with a docker image that I already own in my docker hub repository, you can check it out here: https://hub.docker.com/r/aaron50x/li3-docker/ 

It is a automatic build, so you can have all the framework up and running in just seconds.

Let me know if you're interested.

Thanks in advance.

**Comment by nateabele** [comment]
👍

**Comment by aaron50x** [comment]
Is there something to do, to make it available in the li3.me official documentation?

**Comment by nateabele** [comment]
Good question. @davidpersson I can set up a DockerHub account for the project if you think this is a good idea?

**Comment by davidpersson** [comment]
The docker image contains mongodb and php? I unfortunately don't have any time to maintain other installation methods. If we do this someone else needs to keep an eye on this.
@aaron50x, @nateabele would create a unionofrad dockerhub account, which this image needs to be placed into and can coordinate any steps needed to move the image there. 

Regarding the addition to the manual: You may submit a PR against the repositiory, adding either a simple link to the image from installation/README.md or create a new page in appendencies.

**Comment by aaron50x** [comment]
Yes it contains php 5.6.  It does not contain mongodb, but the pecl mongo driver.  And I could maintain the docker hub account (if you share credentials to my directly to my email), i think it would be good also to have a github repo in the unionofrad account as this is required to have a Dockerfile for automated builds, right now i got this https://bitbucket.org/aaron-opensource/li3-docker :)

**Comment by aaron50x** [comment]
Hi again, please let me know, if you're creating the unionofrad docker account, or simply add a PR in the site source, with the link to my docker image :)

Thanks

**Comment by nateabele** [comment]
@aaron50x I created an org and added you as a maintainer. Feel free to add the image.

**Comment by davidpersson** [comment]
@aaron50x Once you're ready open a PR on the manual repo. @nateabele thanks for handling this.
