### ISSUE TITLE
GLOB_BRACE not defined on some OS

### ISSUE THREAD

**Issue by aaron50x** [UnionOfRAD/lithium#1291]
#I installed php 5.6, with composer and mongodb driver, then I created the quickstart project and started php built-in web server, then go to http://localhost:8080, this notice came up:

Notice: Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' in /home/li3/app/manager-ui/libraries/lithium/core/Libraries.php on line 998

Notice: Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' in /home/li3/app/manager-ui/libraries/lithium/core/Libraries.php on line 999

I fixed it by adding this just right before line 996:
```php
		if(!defined('GLOB_BRACE')) {
			define('GLOB_BRACE', 0x10);
		}
```

I'd like to know if it's a valid fix, if I can make the pull request with this fix :)

Below the screenshot:

![li3-app-error](https://cloud.githubusercontent.com/assets/9508485/16710682/086430b0-45fd-11e6-8d4f-d82902a682ef.png)

**Comment by davidpersson** [comment]
Yes, there are OSs that don't define GLOB_BRACE (http://php.net/manual/en/function.glob.php). However, the documentation is a bit unclear in this regard. It states non-GNU-OSs but BSD has support for it (https://www.freebsd.org/cgi/man.cgi?query=glob&sektion=3).

What kind of OS are you running?

I don't want to sacrifice this feature when we don't have to (the problem can be fixed outside the framework).

**Comment by davidpersson** [comment]
Refs https://github.com/UnionOfRAD/lithium/commit/1636fa080b8cd0cbb2f4a61e68a08add5f88391c

**Comment by davidpersson** [comment]
I've decided to deprecate this feature. Independent of the OS you are using, it seems this feature cannot be used reliably. Thanks for the bug report and PR, which I could not use, as we needed the deprecation.

**Comment by davidpersson** [comment]
Next time let's talk about what could be the best fix first, so I can help you create a PR that gets merged.

**Comment by aaron50x** [comment]
Sure i had this working, with the PR, for sure not the most portable solution, so it's good that you already have a fix.  Thanks :)
