### ISSUE TITLE
Bubble Up View Discovery to 'app' library

### ISSUE THREAD

**Issue by vbresults** [UnionOfRAD/lithium#1294]
I have rewritten this because the previous issue was a misunderstanding on my part; multiple route controller paths are indeed built in and it's a non-issue.  There is an entirely different issue, though.

Libraries/plugins do not inherit layouts from the parent 'app'/plugin.  This is because after failing to discover the layout.ext.php file in the plugin, it does not bubble up and search the parent.

Will write a solution to this, and after testing it, will create a PR.

**Comment by davidpersson** [comment]
You can change this via the Media class:
```
$default = [ 
    'view' => 'lithium\template\View',
    'paths' => [
        'template' => [
            $app . '/views/{:controller}/{:template}.{:type}.php',
            '{:library}/views/{:controller}/{:template}.{:type}.php',
        ],
        'layout' => [
            $app . '/views/layouts/{:layout}.{:type}.php',
            '{:library}/views/layouts/{:layout}.{:type}.php',
        ],
        // 'element'  => '{:library}/views/elements/{:template}.{:type}.php'
    ]
];
Media::type('html', 'text/html', $default);
```
