### ISSUE TITLE
composer install keeps installing lithium in "libraries" dir

### ISSUE THREAD

**Issue by gadelkareem** [UnionOfRAD/lithium#1297]
Suddenly composer install is installing in libraries dir while LITHIUM_LIBRARY_PATH=vendor env var is set.

```"UnionOfRAD/lithium": "dev-master",```

**Comment by davidpersson** [comment]
Lithium libraries will always install into "libraries/" as they are of composer type "lithium-library". Other libraries will by default be installed under "libraries/" as well, as long as you don't change:
https://github.com/UnionOfRAD/framework/blob/master/composer.json#L13

The constant has no effect on composer.

**Comment by gadelkareem** [comment]
Is there a way to change this? I created a syslink but it does not work either?
