### ISSUE TITLE
Router::match does not re-include continuation routes with $context set

### ISSUE THREAD

**Issue by vbresults** [UnionOfRAD/lithium#1304]
If a request comes in to /track/2.0/controller/action, and `track` and `2.0` params are consumed by a continuation route, a url re-constructed with `Router::match` does not contain these parameters.

This is with `$context` set.  As a temporary fix, I'm overriding `base` and plugging the parameters manually; @davidpersson is there another way to do this, or is this an enhancement request?

**Comment by davidpersson** [comment]
Can you paste the relevant route definitions from config/routes.php? This might just be incorrectly defined routes.

**Comment by vbresults** [comment]
::connect in plugin/bootstrap/routes.php:

```php
// incoming url is /track/2.0/records/index.txt

Router::connect("/{:track:\\w+}/{:version:\\d+\\.\\d+}/{:args}", [], ['continue' => true]);

Router::connect("/records/{:action}.txt", ['controller' => RecordsController::class, 'type' => "txt"]);
Router::connect("/{:controller:records|archives}/{:action}.txt");
```

::match in plugin/controllers/RecordsController.php:

```php
Router::match("Records::index", $this->request);  // produces /records/index.txt instead of /track/2.0/records/index.txt
```

**Comment by vbresults** [comment]
@davidpersson Any updates?

**Comment by jails** [comment]
Afaik you must persist them:
```php
Router::connect("/{:track:\\w+}/{:version:\\d+\\.\\d+}/{:args}", [], [
    'continue' => true,
    'persist' => ['track', 'version']
]);
```

**Comment by vbresults** [comment]
Thank you
