### ISSUE TITLE
MongoDate class is deprecated, need to support MongoDB\BSON\UTCDateTime 

### ISSUE THREAD

**Issue by minhna** [UnionOfRAD/lithium#1306]
It's not able to store UTCDateTime object. I'm using php7.
Thank you.

**Comment by davidpersson** [comment]
MongoDB on PHP7 is (unoffically) supported through a wrapper library:
See http://news.li3.me/post/153476416458/releasing-110-beta

li3 2.0 will support MongoDB on PHP7 out of the box:
https://github.com/UnionOfRAD/lithium/pull/1305
