### ISSUE TITLE
Exclude key from Model::all joins

### ISSUE THREAD

**Issue by vbresults** [UnionOfRAD/lithium#1307]
@davidpersson I find that when using MySQL `Flowers::all(['fields' => ["Gardens.location"], 'with' => ['Gardens']])` will include a `id` field (the key) in the `Gardens` result/record.

Additionally, when converting recordset to an array, instead of having a normal array, it's indexed by the primary key `id => record`, which causes problems.

For example, converted to an array, then to JSON, JSON recognizes collections as objects not arrays.  Then we have to put boilerplate code in to normalize.

Is there any way to just have it output a regular array without the primary key as the array key, or otherwise address this at a lower level instead of having to run `array_values`?

**Comment by davidpersson** [comment]
`Collection::to(['indexed' => false])` does what you want for the main collection. At first glance not sure if it also takes care of child records.

http://li3.me/docs/api/lithium/1.1.x/lithium/data/Collection::to()

**Comment by vbresults** [comment]
@davidpersson I see; what about the `id` field that wasn't selected showing up in the records?

**Comment by jails** [comment]
It has been added to be able to perform entities hydration. If `Gardens` were extracted from the database w/o their id, it wouldn't have been possible to know which from garden, flowers belongs to.

**Comment by vbresults** [comment]
@jails Is there any way to recursively remove the `id` field after this hydration if it wasn't selected?

**Comment by davidpersson** [comment]
@vbresults You can use `Set::remove()` to remove the added id key in your normalization process. As @jails explained the primary key is needed here. We cannot change that.

http://li3.me/docs/api/lithium/1.1.x/lithium/util/Set::remove()
