### ISSUE TITLE
RESTful requests: JSON body/data unavailable in Controller

### ISSUE THREAD

**Issue by JasperTey** [UnionOfRAD/lithium#1313]
When sending a RESTful PUT/PATCH/POST request to an endpoint powered by a Lithium controller, the JSON data/body is nowhere to be found.

In `\lithium\action\Request::_init()`, the request content is received and stored:

````
if (!$this->body && $hasBody && $type !== 'html') {
	$this->_stream = $this->_stream ?: fopen('php://input', 'r');
	$this->body = stream_get_contents($this->_stream);
	fclose($this->_stream);
}
````

I verified that by the end of the _init() function, `$this->body` contains the JSON content. However, when the Request reaches the Controller, `$this->request->body` or `$this->request->data` is empty. Somewhere in the request's lifecycle, is the body/data being cleared?

**Comment by davidpersson** [comment]
Hi Jasper, 

Off the top of my head: there's nothing in between the request initialization (and parsing) and the invocation of the controller action, that would reset the data. The only place I currently see where this might happen is in https://github.com/UnionOfRAD/lithium/blob/1.0/action/Request.php#L270. But as you already ruled that out, this might not be it. It'd would great to have a test case, to debug this issue further. Especially interesting would be if $this->data already contains data before line 264.

Thanks!

**Comment by JasperTey** [comment]
I was able to figure it out. In the particular Lithium app this was occurring on, there was some custom code in the bootstrap process, where a new `\lithium\action\Request` object was instantiated:
````
Router::match('/', new Request())
````
The culprit was `new Request()`, which would end up overwriting the body/data of the original request instantiated in index.php, `echo lithium\action\Dispatcher::run(new lithium\action\Request());`

Does this mean that Request is a singleton class that can't/shouldn't be instantiated elsewhere? I didn't realize the second instantiation of `Request` would affect the original `Request` in the lifecycle.

**Comment by davidpersson** [comment]
As it looks the problem is coming from reading from php://input and draining it. Versions before PHP 5.6 did not allow to read from it multiple times. For the moment you have to options: either use PHP 5.6 or set the `'drain'` option (introduced in li3 1.1) to `false` for `Request`s instantiated outside index.php. 

In the longrun we will make it possible to instantiate `Request` multiple times without any problems.
