### ISSUE TITLE
Model::query([/* my options */]) cannot override the default options

### ISSUE THREAD

**Issue by YukinoHayakawa** [UnionOfRAD/lithium#1314]
Hello,

I'm trying to set a set of default query options for my model, however it does not appear to work at all. After examining the code I've found that [the code of query()](https://github.com/UnionOfRAD/lithium/blob/1.0/data/Model.php#L822) performs an array union operation with lhs=default options and rhs=my options, meaning that the overriding options will never be applied since there are already the same keys with null values in the default options. Could you please investigate this issue or am I using it wrongly? Thank you.

**Comment by davidpersson** [comment]
Thanks for the precise bug report. The fix will be contained in the to-be-release 1.0.3 and 1.1.1.
