### ISSUE TITLE
Security issue: Host Header Attack possible

### ISSUE THREAD

**Issue by agustinruatta** [UnionOfRAD/lithium#1317]
Hi!

I think that I have found a security issue in Lithium Framework. I looked for a security email to report this issue in a correct way, but I haven't found (And I think that I should not disclosure it here).

So, what should I do?

**Comment by davidpersson** [comment]
Thanks for your message, please report potential issues to security@li3.me and CC me (nperson@gmx.de). 

Details are described here:
http://li3.me/development

**Comment by agustinruatta** [comment]
Awesome! I sent you an email with the explanation. 

Hope to see your answer!

**Comment by davidpersson** [comment]
I've responded via email. We're looking into it and will update the issue with more details soon.. Thanks again for reporting!

**Comment by davidpersson** [comment]
We've decided to counter these kind attacks by (a) raising awareness by documenting it in our manual (http://li3.me/docs/book/manual/1.x/quality-code/security) and (b) by providing a filter that may intercept the request if the host header contains invalid hostnames.

Read more here: http://news.li3.me/post/161052484503/protection-against-host-header-attacks

Thanks for the initial report, your research and not disclosing this issue publicly and following our guidelines for these kind of issues!

**Comment by agustinruatta** [comment]
Thank you! You were very quickly with the fix, and you did it in a good way.
