### ISSUE TITLE
Unexpected var_dump in database source code

### ISSUE THREAD

**Issue by alexbowers** [UnionOfRAD/lithium#1322]
https://github.com/UnionOfRAD/lithium/blob/5d337263469dc14df1f4c05c226e2f24041f112b/data/source/Database.php#L328

How come there is a var_dump in here printing out the exception message?

This contains the database name, and potentially some sensitive information.

**Comment by davidpersson** [comment]
Fixed in 88c427a49073e2f4ab89d9127e50c022a1fa0054
