### ISSUE TITLE
Support for PHP 7.2?

### ISSUE THREAD

**Issue by niel** [UnionOfRAD/lithium#1325]
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in nzedb/libraries/lithium/core/Object.php on line 37

**Comment by rowanfreeman** [comment]
It's being worked on #1251.

Branch is [struct/deprecate-object](/UnionOfRAD/lithium/tree/struct/deprecate-object).

**Comment by niel** [comment]
Thanks for the info.

**Comment by davidpersson** [comment]
Yes, we're working on it but could use some help #1251 is unfortunately quite a big change to class hierarchy but on the other side gives us the chance to clean some things up.
