### ISSUE TITLE
Support PHP 7.2

### ISSUE THREAD

**Issue by mariuswilms** [UnionOfRAD/lithium#1327]
PHP 7.2 has been released in the beginning of this year and now seems stable enough to be officially supported. Solving this issue involves re-configuring the CI environment to take 7.2 into account, than go ahead and fix all issues that appear.

- [ ] Reconfigure CI environment for 2.0 take PHP 7.2 into account
- [ ] Ensure #1251 is solved and merged into 1.2
- [ ] Have *Object deprecations been merged from 1.2 into 2.0
- [ ] Ensure deprecated *Object classes are removed and not inherited from anymore
- [ ] Fix remaining issues regarding PHP 7.2 compatibility in 2.0

**Comment by niel** [comment]
Any preferences for renaming lithium\core\Object? BaseObject or LiObject are the first that spring to mind. Possibly InstanceObject to counterpoint StaticObject.
I'm looking into this currently, with a simple rename that can be changed to whatever you prefer with search/replace.

**Comment by niel** [comment]
Hi @davidpersson. It was my intention to get branch 1.2 running with PHP 7.2 first (with the class rename and other required changes), as it is needed for people that have already upgraded to it, and then continue with the other tasks as noted in the changelog (refactoring calls to certain Object methods to use the alternatives in Libraries, MergeInheritable, Model, Validator, etc.).

I've refactored use of each() which is also deprecated in PHP 7.2 and have mostly done the Object -> BaseObject switch, just have a weird test failure blocking me - https://travis-ci.org/niel/lithium/jobs/383513373

Getting 1.2 branch working is a high priority for me as I have users that have already upgraded to PHP 7.2, with others planning to do so shortly. Once, that is done I'd be more than happy to look at those last two tasks and see if I can tackle them, in fact I'll take a look tomorrow to get an idea of them, to see if it might be easier job ;-)

**Comment by niel** [comment]
Just took a look at the struct/deprecate-object branch and it seems to be failing on several tests with PHP 7.1. I won't be able to work on it unless those are cleared.

**Comment by davidpersson** [comment]
Usage of `each()` has already been removed in 08d38b2312fbd556249776c7f974b2ad6eba6e47

**Comment by davidpersson** [comment]
> It was my intention to get branch 1.2 running with PHP 7.2 first (with the class rename and other required changes), as it is needed for people that have already upgraded to it,

Totally understandable when you have clients, that need the support now.  Under time pressure I'd suggest to do a quick rename in a fork. However I don't think an ad-hoc solution is good enough for the official repository.

As we need to focus on 2.0, to get it out the door together with other important changes (i.e. the new mongo driver), I needed to decide that the 1.x series will be compatible only up to PHP 7.1.

2.0 will not break all the things, and there are "just" 2-3 tasks left for solving *Object, so I'd suggest you to consider 2.0 as a next upgrade target for your purposes.

**Comment by davidpersson** [comment]
> Just took a look at the struct/deprecate-object branch and it seems to be failing on several tests with PHP 7.1. See https://travis-ci.org/niel/lithium/jobs/384243684
I won't be able to work on it unless those are cleared.

Sorry I've not been precise enough with information on the purpose of the branches. The feauture branch is currently unstable and contains work in progress. I've made it public so contributors who'd like to help have (draft) code to begin with.

The 1.2 branch is stable, when tests are failing there, please file an issue.

**Comment by niel** [comment]
Apart from the PHP 7.2 support, how functional is 2.0? Is feature complete with regards to 1.1/1.2? Is there likely to be much in the way of changhes to the API?

**Comment by davidpersson** [comment]
> Apart from the PHP 7.2 support, how functional is 2.0?
2.0 is fully functional and all tests are passing. 

>  Is it feature complete with regards to 1.1/1.2?
2.0 is still in development and not yet feature complete. We aim for a release this year, so there on the other hand isn't the chance to put too much in it. 

> Is there likely to be much in the way of changes to the API?
Yes, that major release will allow for breaking changes. We plan to exercise this right carefully, i.e. we prefer changes that don't require modifying the manual.

**Comment by JasperTey** [comment]
Is there any progress on this as of April 2019?

**Comment by niel** [comment]
@JasperTey  Last commit to the branch was c4ef68e, which was 30th. July 2018, so I would say no.

**Comment by ericcholis** [comment]
I'm interested in doing whatever I can to help this migration. PHP 7.3 is already four months old and 7.4 is on the horizon for 4th Quarter 2019. PaaS like Google App Engine support 7.2 as a minimum. 

Is the todo list in this issue up to date? Looks like the 2.0 and deprecate-object branches are stagnant.

**Comment by mariuswilms** [comment]
Partial PHP 7.2 support has been enabled for 1.2, in 68932bc6fbe39bd0ed1ce926eae4acab969f44df. Please see the notes regarding usage of the base classes in the changelog.
