### ISSUE TITLE
Fixtures become part of the core framework

### ISSUE THREAD

**Issue by mariuswilms** [UnionOfRAD/lithium#1329]
The core tests already practically depend on the plugin to be present. Having test features in a separate repository caused many small compatibility problems during test runs.

- [x] copy implementation over from li3_fixtures into li3's 2.0 branch, keeping the namespacing from the plugin
- [x] fix any deprecation warnings/errors while making behaviors compatible with 2.0
- [x] check if test coverage is high enough
- [ ] move the documentation from the readme of the plugin into a manual page, preferably under the _quality code_ chapter https://github.com/UnionOfRAD/manual/tree/master/08_quality_code

**Comment by agborkowski** [comment]
- [ ] add snapshot testing like `jest` framework to skip write boilerplate code

**Comment by mariuswilms** [comment]
The plugin will be integrated into 1.2

**Comment by mariuswilms** [comment]
Integrated in 8452d38c3771914371e6271fec145699ee081e5c
