### ISSUE TITLE
li3 2.0 trait not found

### ISSUE THREAD

**Issue by alexanderhaensch** [UnionOfRAD/lithium#1339]
with branch 2.0 I get:
"PHP message: PHP Fatal error:  Trait 'lithium\core\MergeInheritable' not found in /var/www/bestellsystem/libraries/lithium/action/Controller.php on line 46"

I cannot make sense out of that. Because MergeInheritable.php exists.

**Comment by nateabele** [comment]
Were you able to resolve this? If not, what OS are you on? What does the directory layout of your application look like? Do you have any customizations to `config/bootstrap/libraries.php`? Thanks.

**Comment by nateabele** [comment]
Please see the 2.0 migration guide: https://github.com/UnionOfRAD/lithium/blob/2.0/MIGRATING.md

It is likely that you need to update your application’s `config/bootstrap/libraries.php` file.
