### ISSUE TITLE
Remove {Static,}Object for Shallow Class Hierachy

### ISSUE THREAD

**Issue by mariuswilms** [UnionOfRAD/lithium#1341]
Base classes are set to be removed in 2.0, they have been deprecated in 1.2. 

- [ ] Remove `_init()` usage, where tests rely on skipping the initialization phase, change classes to accept an alternative less-generically named option to skip certain parts of the initialization phase. The `_init()` class methods will than need to be merged into the constructor.
- [ ] Classes which rely on auto configuration currently present in the base class' `_init()` 
should make use of `AutoConfigurable` instead. 
- [ ] Have the classes that were one level above the old base classes, set `$_config`
- [ ] Stop classes from extending deprecated base classes
- [ ] Ensure all unit tests are green
- [ ] Ensure all integration tests are green

The `_init` removal is being worked upon in the `init-removal` branch.

**Comment by nateabele** [comment]
I ended up maintaining the `_init()` functionality, as the complexity trade-off is low compared to the ability to bootstrap a class without its dependencies, and feedback from the community was that the migration burden would have been too significant.

This functionality has been incorporated into the `AutoConfigurable` trait.
