### ISSUE TITLE
Framework status?

### ISSUE THREAD

**Issue by cgilbertda** [UnionOfRAD/lithium#1348]
Is lithium still being actively maintained? How is the support for php 7.3 or 7.4 in v1.2.0? I see mentions of partial support for 7.3, are there any major issues if upgrading php to 7.3? Any documentation on migrating from v1.0.0 to v1.2.0?

**Comment by mariuswilms** [comment]
Please see #1349, regarding your other questions, please see _Series Compatibility_ on https://li3.me/versions
