### ISSUE TITLE
Maintainer/s wanted

### ISSUE THREAD

**Issue by mariuswilms** [UnionOfRAD/lithium#1349]
Hello, 

are you interested in becoming the next maintainer and lead developer of the framework? In this position you'll be able to define the roadmap towards taking the next important step for the project, by preparing and releasing the 2.0 version. I'm available to answer any questions, feel free to directly comment on this issue or contact me via email: myGitHubUsername@mailbox.org.

Thanks
Marius

**Comment by ghost** [comment]
Hey @mariuswilms,
I really love the way you have think lithium and i have saw nobody is trying to keep it alive, so i wanted to now if i have the possibility to become is Maintainer, i have start to use PHP 7 years ago so i'm not to bad and not to good. 

Have a great day/night.
Olivier
