### ISSUE TITLE
Framework upgrade for latest PHP 

### ISSUE THREAD

**Issue by Bharadwajrv** [UnionOfRAD/lithium#1350]
Good morning, just wondering anyone know will there be upgrade of Li3 will be released soon ?

In the "Code" tab, I can see, current framework supports  PHP 7.3 which will be out-of-support in 5 months time (Dec 2021) and interested to know when the upgrade framework to support PHP 7.4 or PHP8.0 will be release please? 

Regards
Venu

**Comment by ghost** [comment]
Hi @Bharadwajrv, good to know you want to use or continue to use li3.

For now the creator search for maintainer/s, i have ask to be able to continue the project but no answer has been received yet.

Best Regards

**Comment by Bharadwajrv** [comment]
thanks @GodhoodHorus. Really appreciate the quick response.

**Comment by phishy** [comment]
Hey all!

My team absolutely must work on this PHP 8 upgrade, so we're looking to start planning it out shortly. Stay tuned.

Preliminary Findings:

- [ ] remove references to deprecated Serializable
- [ ] make iterators conform to requirements of PHP8

**Comment by nateabele** [comment]
Working with @phishy on this and targeting PHP 8.1-compatible release by November at the latest. Let us know if you'd like to help!
