### ISSUE TITLE
li3 upgrade to php 8

### ISSUE THREAD

**Issue by sonusen235** [UnionOfRAD/lithium#1360]
Hello, We want to upgrade our li3 project from php 7 version to php 8.
I want to know, does li3 supports latest php 8 version. will there be any consequences if we upgrade to php 8 version.

**Comment by nateabele** [comment]
The 2.0 branch will target PHP 8.1 and be released in November. Thanks.

**Comment by sonusen235** [comment]
@nateabele Thank you so much for the response, We will be eagerly waiting for the PHP 8.1 upgrade.

**Comment by sonusen235** [comment]
Hi @nateabele, Can you please tell us the release date when we can except PHP 8.1  upgrade

**Comment by nateabele** [comment]
Shooting for early November, so, in a few weeks. Let me know if you'd like to contribute or help test against your app. Thanks.

**Comment by sonusen235** [comment]
@nateabele Thanks for the info, Yes we would like to contribute testing against our app, Thanks

**Comment by nateabele** [comment]
@sonusen235 We should have a dev release out in the next few days. Please join our new Slack org and we'll announce when the release is available, then you can report back your testing findings. https://join.slack.com/t/li3-group/shared_invite/zt-1i7x13pmc-sG25FR8Yg0ztUC8m46Q_tg

**Comment by Er-Kalpesh** [comment]
any further updates regarding php8 support?

I am getting this error on php8.1:

`Fatal error: Uncaught Error: Class "lithium\core\ObjectDeprecated" not found in /var/www/XYZ/app/b/libraries/lithium/util/Collection.php:78 Stack trace: #0 /var/www/XYZ/app/b/app/config/bootstrap/libraries.php(88): require() #1 /var/www/XYZ/app/b/app/config/bootstrap.php(32): require('...') #2 /var/www/XYZ/app/cd-admin/includes/lithium.php(3): require('...') #3 /var/www/XYZ/app/cd-admin/includes/connect.php(4): require('...') #4 /var/www/XYZ/app/index.php(10): require('...') #5 {main} thrown in /var/www/XYZ/app/b/libraries/lithium/util/Collection.php on line 78`
