### ISSUE TITLE
'with' count 1, not 0

### ISSUE THREAD

**Issue by only4r** [UnionOfRAD/lithium#1369]
Hey,

I think my Lithium version: v0.10.0

My problem:

models:
models/BlogPostsAttachment.php
models/BlogPost.php

controller:
```
$posts = BlogPost::all( array( 'with' => array( 'BlogPostsAttachment' ) ) );
$posts = $posts -> to( 'array' );
```

view:
`var_dump( $posts['blog_posts_attachments'] ); // array( 0 => array( 'id' => NULL, 'title' => NULL ) )`

Why generate this NULL item/row? The count( $posts['blog_posts_attachments'] ) is 1, but the real is 0.

If attachments is 1. The count is 1. This is okay. The problem only if empty the attachments. If empty, generate NULL array item.

Please help me. Thanks.

**Comment by nateabele** [comment]
v0.10.0 is not supported, sorry.
