### ISSUE TITLE
PHP 8.3 compatibility

### ISSUE THREAD

**Issue by adamroyle** [UnionOfRAD/lithium#1371]
PHP 8.3 is now stable - can the composer requirement be adjusted?

**Comment by nateabele** [comment]
i.e. `"php": "~8.1.0 || ~8.2.0 || ~8.3.0"`?

We should probably set up a build matrix for the test suite first, but in principle, yes.

**Comment by adamroyle** [comment]
@nateabele Yep, that's what I'm referring to.
