### ISSUE TITLE
Validating empty arrays

### ISSUE THREAD

**Issue by daschl** [UnionOfRAD/lithium#22]
Note: this ticket is ported over from rad-dev.org and consolidates a bunch of tickets of the same topic.

The enhancement states some way of validating if an array is empty or not (which is handy vor validating selects, checkboxes and other stuff).

Here is a proposal for a recursive approach to test for empty arrays. It basically extends the current pattern recursively on arrays. Some test cases included. Feel free to talk about and/or contribute!

	//'notEmpty'     => '/[^\s]+/m',
	'notEmpty'	   => function($value, $format = null, array $options = array()) {
		$pattern = '/[^\s]+/m';
		$arrayTest = function($arr) use ($pattern, &$arrayTest) {
			foreach($arr as $k => $v) {
				if(is_array($v)) {
					return $arrayTest($v, $arrayTest);
				} else {
					if(preg_match($pattern, $v)) {
						return true;
					}
				}
			}
			return false;
		};
		return $arrayTest((array)$value);
	},

	public function testNotEmptyRule() {
		$this->assertTrue(Validator::isNotEmpty('abcdefg'));
		$this->assertTrue(Validator::isNotEmpty('fasdf '));
		$this->assertTrue(Validator::isNotEmpty('fooo' . chr(243) . 'blabla'));
		$this->assertTrue(Validator::isNotEmpty('abÃ§ÄÄ•Ê‘Ê˜Ï€Ð¹'));
		$this->assertTrue(Validator::isNotEmpty('JosÃ©'));
		$this->assertTrue(Validator::isNotEmpty('Ã©'));
		$this->assertTrue(Validator::isNotEmpty('Ï€'));
		$this->assertFalse(Validator::isNotEmpty("\t "));
		$this->assertFalse(Validator::isNotEmpty(""));
		
		$this->assertTrue(Validator::isNotEmpty(array('foo', 'bar')));
		$this->assertTrue(Validator::isNotEmpty(array(array('foo'))));
		$this->assertFalse(Validator::isNotEmpty(array()));
		$this->assertFalse(Validator::isNotEmpty(array(array())));
		$this->assertFalse(Validator::isNotEmpty(array("", "\t ")));
		$this->assertFalse(Validator::isNotEmpty(array(array(""), "\t ")));
	}

**Comment by davidpersson** [comment]
Finally ... it took some years :)  But:
🕙 

Testing and validating inside arrays can now be done using the dot syntax. It's also now possible to validate an entire array in an validator aa9b5e8bdb39ddacc2b9cd5b05c8564e80eca21f wich allows to implement the validator above in userland.
