### ISSUE TITLE
Protect to mass-assignment vulnerability?

### ISSUE THREAD

**Issue by Leechael** [UnionOfRAD/lithium#370]
Since this problem exists for a long time, codes like:

```PHP

if ($this->request->data) {
  $success = $entity->save($this->request->data);
}

```

When we can not guarantee fields that no along modified in this controller/action or this session (relate to a explicit user). Since we can do protection via validations (set up lot of validation rules and do lot of validation on context), maybe we can get a smarter way?

Any idea?

References:
* https://github.com/blog/1068-public-key-security-vulnerability-and-mitigation

**Comment by davidpersson** [comment]
I've added a _Security_ chapter to the manual:
http://li3.me/docs/manual/security

Feel free to expand it by contributing to the manual at:
https://github.com/UnionOfRAD/manual

Closing this as per @nateabele there is no general fix that the framework can provide for this issue. Instead use a combination of already available techniques the framework _already_ provides (whitelist, secured form field, access control).
