### ISSUE TITLE
Isolating tests: Autoisolate class setup/teardown

### ISSUE THREAD

**Issue by jails** [UnionOfRAD/lithium#470]
Because of static class, isolating tests are a difficult task.
Indeed configuring classes using `Classname::config()` can have repercussions on other tests.

For example `lihium\tests\cases\data\collection\DocumentSetTest` can't pass on its own.
But pass if it executed just after `lihium\tests\cases\data\entity\DocumentTest`.
In this case `DocumentTest` correctly configure the `MockDocumentPost` and its `_schema` attribute to the correct `lihium\source\mongo_db\Schema` class. This explain why `DocumentSetTest` executed after `DocumentTest` works.

Another headache was when all my model's source name containing a "d" instead of "t". (ex Author::meta('source') return 'audhor' instead of 'author'). I first thought that my computer was dead. but after digging a little I can see the following piece of code in `lithium\tests\integration\g11\CatalogInflectorTest` :
<pre>
$data = array(
'transliteration' => array(
	't' => 'd',
	'&' => 'und'
));
Catalog::write('runtime', 'inflection', 'de', $data);

Inflector::rules('transliteration', 
        Catalog::read('runtime', 'inflection.transliteration', 'de'));
</pre>

This explain why `Inflector::slug()` used in the table name generation translate all 't' to 'd'

`\lithium\tests\cases\data\ModelTest` is also a  place where isolation can be an issue. Indeed when a model is used an instance is created "forever" with `Model::_object()`. So variables like Model::_schema, Model::_finders are initialized and generate conflicts.

My current attempt for this last issue is renew the instance on each `Model::config` call (by overrinding the `Model::config()`).

To a lesser extent there's also pieces of code like the following. I don't think the isolation test should be managed in tests imo.

<pre>
public function setUp() {
	$this->request = new Request();
	$this->_routes = Router::get();
	Router::reset();
}

public function tearDown() {
	Router::reset();
	foreach ($this->_routes as $route) {
		Router::connect($route);
	}
}
</pre>

Don't hesitate to share here your experience and/or solutions on these issue

**Comment by davidpersson** [comment]
Isolation should be left to the developer creating the test. It's part of creating a test to also guarantee proper isolation. As there are already enough methods in the framework to do this and all test seem isolated, I'm closing this issue.
