### ISSUE TITLE
li3 verbose does not show all exceptions in case of fatal

### ISSUE THREAD

**Issue by hans-d** [UnionOfRAD/lithium#517]
Playing around with testing, and probably my set up is not yet complete. I have multiple lines reporting having an exception, but I get no useful information, such as: the exception raised, and its context.

```
[exception] on line   14 in app\controllers\RelatieAppService::startNieuweRelatie()
[exception] on line   86 in -::session_start()
[exception] on line   86 in -::session_start()
[exception] on line   25 in app\controllers\RelatieAppService::startNieuweRelatie()
[exception] on line   25 in app\controllers\RelatieAppService::startNieuweRelatie()

Fatal error: Unsupported operand types in [...]\app\controllers\RelatieAppService.php on line 25

Call Stack:
[...]
```

The fatal error I could trace down to a non-existing variable... 

Normally all exceptions are shown.

**Comment by davidpersson** [comment]
I don't want to add more features to the test command. There are other places that need more work. You can achieve the desired behavior by applying a filter to `Unit::run()` and rethrow the exception after it was handled.
