### ISSUE TITLE
Coding style [PSR-2]

### ISSUE THREAD

**Issue by djordje** [UnionOfRAD/lithium#526]
Hi,

Do you have plants to update Lithium's internal coding styles to [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) or we should continue to use coding style defined in Lithium docs?

Best regards

**Comment by dereuromark** [comment]
You should probably still use phpcs sniffing in PRs and Travis runs.
You can just use https://github.com/php-fig-rectified/psr2r-sniffer - which seems to be exactly what you are using anyway :) For saner code style.
