### ISSUE TITLE
Option for li3 test to only show summaries

### ISSUE THREAD

**Issue by hans-d** [UnionOfRAD/lithium#544]
li3 test has currently an option `plain` that only shows the dotted progress. There is not option just to show the summary: number of tests passed/failed, and the exceptions/fails.

When including li3 test in a phing build, output of running li3 is captured/buffered before it is shown (called via a php exec). Hence the dotted progress has no value here. Showing just the summaries would be a good thing to have.

**Comment by davidpersson** [comment]
As the buffering is unnecessary but not breaking anything, I'm closing this as we want to keep the command as lean as possible.
