### ISSUE TITLE
Adding a new Media type and Content Negotiation

### ISSUE THREAD

**Issue by mehlah** [UnionOfRAD/lithium#600]
Adding a custom Media type with  `Media::type('foo', 'application/foo', $options)`, 2 times, one with `$options['conditions']`, and the other without conditions, makes the last set one, the only active one.

I would expect that the both type handlers co-exists, and the `$options['conditions']` assertion let Lithium pick one.

Is that a bug or a feature ?
##### A simple use case:

Adding a 'json' Media type with default views paths, and without an 'encode' closure, to write custom json responses (as views).
The conditions could be array('json' => true), to only handle responses for urls like `/posts.json`.

How to make it work, side by side with the default `json` type encoder?

A longer description of a use case: https://github.com/mehlah/li3_jbuilder/blob/master/README.md

**Comment by agborkowski** [comment]
``````````
Media::type(
    'ajax',
    ['text/html'],
    [
        'view' => 'lithium\template\View',
        'paths' => [
            'template' => [
                '{:library}/views/{:controller}/{:template}.ajax.php',
                '{:library}/views/{:controller}/{:template}.html.php',
            ],
            'layout' => false,
            'element' => [
                '{:library}/views/elements/{:template}.ajax.php',
                '{:library}/views/elements/{:template}.html.php'
            ]
        ],
        'conditions' => ['ajax' => true]
    ]
);
````````````
i dont know where is bug but after few yr working this part li3 starts loading layout any suggestion how i can debug this ? any changes in li3 core negotiation ? when i place is('ajax') return true in controller why media is loading layout ;/ when i add action.ajax media handle layout false

**Comment by nateabele** [comment]
I believe [this](https://github.com/UnionOfRAD/lithium/commit/a892430ad4fc800a674b353f321382fd476c3170) is the only recent change to `Media`... not sure that would affect it though. You're sure it's not something in your own code?

**Comment by agborkowski** [comment]
YUP i think this is it ill try li3 b4 this patch and after..
