### ISSUE TITLE
Reduce overhead in Form Signing

### ISSUE THREAD

**Issue by Ciaro** [UnionOfRAD/lithium#839]
Hello guys

The current implementation of CSRF protection in Lithium seems to have a lot of unneeded overhead. It uses sha512 by default, but even if you define md5 as a type, you are still getting tokens generated by 'php::crypt'. This can add up if you use a couple of forms one a page. 

Could we not accomplish the same functionality by just using plain-old md5 tokens? 

Please do correct me if I'm wrong about this :)

Best regards,

Ciaro

**Comment by nateabele** [comment]
Fixed.
