### ISSUE TITLE
\lithium\action\Request::accepts($type) does not return boolean per documentation

### ISSUE THREAD

**Issue by al-the-x** [UnionOfRAD/lithium#856]
From `lithium\action\Request::accepts()` docblock (and thus generated documentation):

	/**
	 * Returns information about the type of content that the client is requesting.
	 *
	 * @see lithium\net\http\Media::negotiate()
	 * @param $type mixed If not specified, returns the media type name that the client prefers,
	 *              using content negotiation. If a media type name (string) is passed, returns
	 *              `true` or `false`, indicating whether or not that type is accepted by the client
	 *              at all. If `true`, returns the raw content types from the `Accept` header,
	 *              parsed into an array and sorted by client preference.
	 * @return string Returns a simple type name if the type is registered (i.e. `'json'`), or
	 *         a fully-qualified content-type if not (i.e. `'image/jpeg'`), or a boolean or array,
	 *         depending on the value of `$type`.
	 */

In practice, however, the `accepts()` method returns the negotiated content name, e.g. "html" or "json", _not_ true / false if `$type` matches. Which should it be so that I can submit a PR to fix?

**Comment by davidpersson** [comment]
The `accepts()` method works only with short media type names i.e. 'json'. Also note that it only knows about types that are registered via `Media::type()`.

**Comment by al-the-x** [comment]
Thanks for finally correcting this, @davidpersson. Sadly, I'm not using Lithium anywhere anymore. Too much wheel reinvention syndrome...

**Comment by davidpersson** [comment]
Ha -- no worries. Still the bug is valid thus I'm reopening and will close once the patch has been merged.

**Comment by nateabele** [comment]
Fixed in #1180.
