### ISSUE TITLE
Form Signatures listing different fields between form render and submit, hashing not working

### ISSUE THREAD

**Issue by cinaeco** [UnionOfRAD/lithium#998]
I was trying to use form signing when I ran into issues:

1. `template\helper\Security`'s filter on '_defaults' also picks up label names e.g. `$state[$id]['fields']` might contain `'AddressesPostCode'` and `'address.postCode'` field names, whereas when checking the request data, only the `'address.postCode'` field would exist. Signatures on forms with labels would never agree. I bypassed this temporarily by putting in a check for `$params['method'] == 'label'` and skipping those elements.

2. When `FormSignature::check()` calls `FormSignature::key()`, it has it's fields array with field names as values, instead of as keys as `template\helper\Security`'s filters do. I bypassed this temporarily by putting in an `array_flip()` before calling `key()`.

3. I then tried to submit a form, but first mangled a field name, thinking this would produce an error, but it didn't. The hashes for submitting a form with and without a mangled field name remain the same e.g.

original field (1 out of 14 others): 'parent.mobile'
original hash: '$2a$10$NuNTOeXv4OHpPJtbdAmfReEtZeKhI9F9xBL8qGvbO.kFHM4KzJoRK'
 
mangled field (1 out of 14 others): 'parensfsdfsdfsdfsdft.mobile'
mangled hash: '$2a$10$NuNTOeXv4OHpPJtbdAmfReEtZeKhI9F9xBL8qGvbO.kFHM4KzJoRK'

Have I misunderstood how this is supposed to work? Should the field names make a difference to the hash?

**Comment by nateabele** [comment]
Fixed.
